## Bases

When working with vector spaces, or subspaces, it is often useful to express arbitrary vectors as linear combinations of a set of given vectors known as a basis.  A **basis** for a vector space (or subspace) is a collection of linearly indpendent vectors that span the space.  

Given a basis $\{V_1, V_2, V_3, ... V_n\}$ for the vector space $\mathbb{R}^n$, the definition implies that any vector $Y$ in $\mathbb{R}^n$ can be uniquely expressed as a linear combination of the basis vectors.  That means that the vector equation $c_1V_1 + c_2V_2 + ... c_nV_n = Y$ has a unique solution.  This statement is a result of our earlier conclusions about systems of equations.

Let $A$ be the $n\times 1$ matrix with the basis vectors $V_1$, $V_2$, ... $V_n$ as its columns, and $X$ the vector of weights $c_1$, $c_2$, ... $c_n$.  In order to express $Y$ as a linear combination of the basis vectors, we need to solve the linear system $AX = Y$.  Since the basis vectors span $\mathbb{R}^n$ we know that the system is consistent for any $Y$ in $\mathbb{R}^n$.  This implies that $A$ must have a pivot in every row.  The fact that the basis vectors are linearly independent implies that the system must have a unique solution.  This means there can be no free variables in ths system, which means that there must be a pivot in each column.  The RREF of an $n\times n$ matrix with a pivot in every row and column is the $n\times n$ identity matrix.   

### Example 1:  Basis for $\mathbb{R}^5$

The following set of vectors form a basis for $\mathbb{R}^5$.


$$
\begin{equation}
V_1 = \left[ \begin{array}{r} -3 \\ 3 \\ 2 \\ -3 \\ -2 \end{array}\right] \hspace{0.7cm} 
V_2 = \left[ \begin{array}{r} 3 \\ 3 \\ 2 \\ -1 \\ 3  \end{array}\right] \hspace{0.7cm}
V_3 = \left[ \begin{array}{r} 2 \\ 0 \\ -2 \\ 2 \\ 2 \end{array}\right] \hspace{0.7cm}
V_4 = \left[ \begin{array}{r} -3 \\ -1 \\ 2 \\ -1 \\ 3 \end{array}\right] \hspace{0.7cm}
V_5 = \left[ \begin{array}{r} -2 \\ 0 \\ -3 \\ 3 \\ -2 \end{array}\right] 
\end{equation}
$$

To verify these vectors form a basis, we need to check that a matrix with these vectors as columns has pivots in each row and column. 

In [1]:
A = np.array([[-3,3,2,-3,-2],[3,3,0,-1,0],[2,2,-2,2,-3],[-3,-1,2,-1,3],[-2,3,2,3,-2]])
print(lag.FullRowReduction(A))

NameError: name 'np' is not defined

### Example 2: Basis for a subspace of $\mathbb{R}^3$

The following set of vectors forms a basis for the subspace of $\mathbb{R}^3$ that consists of vectors with middle entry equal to zero.

$$
\begin{equation}
U_1 = \left[ \begin{array}{r} 1 \\ 0 \\ 2 \end{array}\right] \hspace{1cm} 
U_2 = \left[ \begin{array}{r} 0 \\ 0 \\ 1 \end{array}\right] 
\end{equation}
$$

We need to check that any vector in $\mathbb{R}^3$ with middle entry equal to zero can be expressed as a linear combination of $U_1$ and $U_2$, and we need to check that $\{U_1, U_2 \}$ is a linearly independent set.  We define $A$ as a matrix with $U_1$ and $U_2$ as the columns.


$$
\begin{equation}
A = \left[ \begin{array}{rr} 1 & 0 \\ 0 & 0 \\ 2 & 1 \end{array}\right] 
\end{equation}
$$

To determine if $\{U_1, U_2\}$ is linearly independent, we need to find out if the homogeneous system $AX=0$ has any nontrivial solutions.  If both columns of $A$ contain a pivot, there are no nontrivial solutions and the vectors are linearly independent.  Since there are only two columns, it suffices to check that one column is not a scalar multiple of the other, but we will compute the RREF of $A$ for the sake of completeness.

In [12]:
A = np.array([[1,0],[0,0],[2,1]])
print(lag.FullRowReduction(A))

[[1. 0.]
 [0. 1.]
 [0. 0.]]


To determine if $U_1$ and $U_2$ span the subspace, we need to check if an arbitrary vector $Y$ with middle entry equal to zero can be expressed as a linear combination of the two vectors.  That is, given any values of $y_1$ and $y_3$, can we always find $c_1$ and $c_2$ to solve the vector equation?  

$$
\begin{equation}
c_1\left[ \begin{array}{r} 1 \\ 0 \\ 2 \end{array}\right] +
c_2\left[ \begin{array}{r} 0 \\ 0 \\  1 \end{array}\right] =
\left[ \begin{array}{c} y_1 \\ 0 \\ y_3 \end{array}\right] 
\end{equation}
$$

In this example it is clear that we can take $c_1 = y_1$ and $c_2 = y_3 - 2y_1$ by using substitution.  

### Example 3: Solution set of a homogeneous system

Consider the homogeneous system $AX=0$ where $X$ is a vector in $\mathbb{R}^4$ and $A$ is the following $2\times 4$ matrix.

$$
\begin{equation}
A = \left[ \begin{array}{rrrr} 1 & 0 & 3 & -2 \\ -2 & 1 & 3 & 0 \end{array}\right] 
\end{equation}
$$

In [14]:
A = np.array([[1,0,3,-2],[-2,1,3,0]])
print(lag.FullRowReduction(A))

[[ 1.  0.  3. -2.]
 [ 0.  1.  9. -4.]]


In this system, $x_3$ and $_4$ are free variables.  If we set $x_3 = t$, and $x_4=s$, then $x_1 = 2s -3t$ and 
$x_2 = 4s -9t$.  we can write the components of a general solution vector $X$ in terms of these parameters.

$$
\begin{equation}
X = \left[ \begin{array}{r} x_1 \\ x_ 2 \\ x_ 3 \\ x_4 \end{array}\right] =  
t\left[ \begin{array}{r} -3 \\ -9 \\  1 \\ 0 \end{array}\right] +
s\left[ \begin{array}{r} 2 \\ 4 \\ 0 \\ 1  \end{array}\right] 
\end{equation}
$$

In this form we can see that any solution of $AX=B$ must be a linear combination of the vectors $W_1$ and $W_2$ defined as follows.


$$
\begin{equation}
W_1 = \left[ \begin{array}{r} -3 \\ -9 \\  1 \\ 0 \end{array}\right] \hspace{1cm}
W_2 = \left[ \begin{array}{r} 2 \\ 4 \\ 0 \\ 1  \end{array}\right] 
\end{equation}
$$

The set $\{W_1, W_2\}$ is linearly independent and forms a basis for the set of solutions to $AX=0$.

### Exercises

- Find a basis for the set of solutions to the system $PX=0$ where $P$ is defined as follows.

$$
\begin{equation}
A = \left[ \begin{array}{rrrr} 1 & 0 & 3 & -2 & 4 \\ -1 & 1 & 6 & -2 & 1 \\ -2 & 1 & 3 & 0 & -3 \end{array}\right] 
\end{equation}
$$

- Determine if the following set of vectors is a basis for $\mathbb{R}^4$.  Give justification with an appropriate calculation.

- Give an example of a set of three vectors that does **not** form a basis for $\mathbb{R}^3$.  Provide a calculation that shows why the example is not a basis.


### Dimension

We now examine some sets of vectors that do not form bases.  By looking at these non-example we will uncover a concept that is related directly to bases.


The following set of vectors is **not** a basis for $\mathbb{R}^5$.


$$
\begin{equation}
V_1 = \left[ \begin{array}{r} -3 \\ 3 \\ 2 \\ -3 \\ -2 \end{array}\right] \hspace{0.7cm} 
V_2 = \left[ \begin{array}{r} 3 \\ 3 \\ 2 \\ -1 \\ 3  \end{array}\right] \hspace{0.7cm}
V_3 = \left[ \begin{array}{r} 2 \\ 0 \\ -2 \\ 2 \\ 2 \end{array}\right] \hspace{0.7cm}
V_4 = \left[ \begin{array}{r} -3 \\ -1 \\ 2 \\ -1 \\ 3 \end{array}\right] \hspace{0.7cm}
V_5 = \left[ \begin{array}{r} -2 \\ 0 \\ -3 \\ 3 \\ -2 \end{array}\right] \hspace{0.7cm}
V_6 = \left[ \begin{array}{r} -1 \\ 0 \\ 2 \\ 2 \\ 1 \end{array}\right] 
\end{equation}
$$

Although we can assemble a $5\times 6$ matrix with these vectors as the columns, and compute the RREF as before, we should expect to find that the matrix does not have a pivot in each column due to its shape.  Recall that each row can have at most one pivot, which means that the matrix has at most 5 pivots.  Since there are 6 columns, one of the columns does not have a pivot.  This shows that the set of vectors is linearly dependent, and thus not a basis.

In [10]:
B = np.array([[-3,3,2,-3,-2,-1],[3,3,0,-1,0,0],[2,2,-2,2,-3,2],[-3,-1,2,-1,3,2],[-2,3,2,3,-2,1]])
print(lag.FullRowReduction(B))

[[ 1.   0.   0.   0.   0.  -1.6]
 [ 0.   1.   0.   0.   0.   1.8]
 [ 0.   0.   1.   0.   0.  -2.9]
 [ 0.   0.   0.   1.   0.   0.6]
 [ 0.   0.   0.   0.   1.   1.8]]


The following set of vectors is **not** a basis for $\mathbb{R}^5$.


$$
\begin{equation}
V_1 = \left[ \begin{array}{r} -3 \\ 3 \\ 2 \\ -3 \\ -2 \end{array}\right] \hspace{0.7cm} 
V_2 = \left[ \begin{array}{r} 3 \\ 3 \\ 2 \\ -1 \\ 3  \end{array}\right] \hspace{0.7cm}
V_3 = \left[ \begin{array}{r} 2 \\ 0 \\ -2 \\ 2 \\ 2 \end{array}\right] \hspace{0.7cm}
V_4 = \left[ \begin{array}{r} -3 \\ -1 \\ 2 \\ -1 \\ 3 \end{array}\right] \hspace{0.7cm}
\end{equation}
$$

The matrix made up of these column vectors has 5 rows and 4 columns.  There are at most 4 pivots since each column can contain no more than 1 pivot.  This means that there is at least one zero row in the RREF, which implies that the system $AX = B$ is not consistent for every $B$ in $\mathbb{R}^5$.

In [15]:
B = np.array([[-3,3,2,-3],[3,3,0,-1],[2,2,-2,2],[-3,-1,2,-1],[-2,3,2,3]])
print(lag.FullRowReduction(B))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


These two examples illustrate why any set of vectors that does not contain exactly five vectors cannot be a basis for $\mathbb{R}^5$.  We might suspect that exactly five vectors are needed because the space is five-dimensional, and this is almost correct.  It is more accurate to say that $\mathbb{R}^5$ is five-dimensional *because a basis for the space must have five vectors*.  The **dimension** of a vector space (or subspace) is defined as the number of vectors in any basis for the space.

### Exercise

- Calculate the dimension of a span of given vectors $V_1, V_2, V_3, V_4$.

### Coordinates

In order to discuss the concept of coordinates, it is useful to label the bases that under discussion.  We will opt to use greek letters for these labels in order to keep the notation for bases distinct.  Suppose then we are given a basis $\beta = \{V_1, V_2, V_3, ... V_n\}$ and a vector $X=c_1V_1 + c_2V_2 + ... c_nV_n$.  The weights $c_1$, $c_2$, ... $c_n$ are called the **coordinates** of X with respect to the basis $\beta$.  It is only natural to collect these weights into an array.  Despite potential confusion, this array is referred to as the coordinate vector.

### Exercises