## Inner Products

In [7]:
import laguide as lag
import numpy as np
import scipy.linalg as sla
%matplotlib inline
import matplotlib.pyplot as plt
import math

**Exercise 1:** Create a Python function named $\texttt{Magnitude}$ that accepts as an argument vector in the form of a NumPy array object with shape $n\times 1$, and returns the magnitude of that vector.


In [2]:
def Magnitude(U):
    ''' 
    Magnitude(U)
    
    Magnitude computes the magnitude of U based on the Euclidean inner product
    
    Parameters
    ----------
    U : NumPy array object of dimension nx1
    
    Returns
    -------
    product: float
    '''
    # Check shape of U
    if (U.shape[1] != 1):
        print("Magnitude only accepts column vectors.")
        return
    
    magnitude = math.sqrt(DotProduct(U,U))
    return magnitude

**Exercise 2:** Use the $\texttt{random}$ module of NumPy to generate random $4\times 1$ vectors $U$, $V$, and $W$, and a random scalar $k$.  Verify the algebraic properties of the dot product listed above.  Try to make use of a conditional statement to check each statement.

We want to verify that the following equations hold for random $4 \times 1$ vectors $U, V,$ and $W$ and scalar $k$.
1. $U\cdot V = V\cdot U$
2. $U\cdot(V + W) = U\cdot V + U\cdot W$
3. $(kU)\cdot V = k(U\cdot V)$
4. $U\cdot U \ge 0$

In [6]:
U = np.random.randint(20,size=(4,1))
V = np.random.randint(20,size=(4,1))
W = np.random.randint(20,size=(4,1))
k = np.random.randint(20)

print(U,'\n')
print(V,'\n')
print(W,'\n')
print(k,'\n')

if (lag.DotProduct(U,V) == lag.DotProduct(V,U)):
    print("The dot product is commutative. \n")
if (lag.DotProduct(U,V+W) == lag.DotProduct(U,V) + lag.DotProduct(U,W)):
    print("The dot product distributes over vector addition. \n")
if (lag.DotProduct(k*U,V) == k*lag.DotProduct(U,V)):
    print("The dot product is associative with respect to scalar multiplication. \n")
if (lag.DotProduct(U,U) >= 0):
    print("The dot product of a vector with itself is greater than or equal to 0 \n")

[[ 7]
 [19]
 [11]
 [11]] 

[[8]
 [0]
 [6]
 [1]] 

[[12]
 [14]
 [12]
 [18]] 

9 

The dot product is commutative. 

The dot product distributes over vector addition. 

The dot product is associative with respect to scalar multiplication. 

The dot product of a vector with itself is greater than or equal to 0 



**Exercise 3:** Let $X$ and $Y$ be the following vectors.

$$
\begin{equation}
X = \left[ \begin{array}{r} 3 \\ -1 \\ 2  \end{array}\right] \hspace{1cm} 
Y = \left[ \begin{array}{r} 4 \\ 2 \\ 0  \end{array}\right] 
\end{equation}
$$

$(a)$ Determine the angle between $X$ and $Y$.  (*You will need the $\texttt{acos}$ function in Python's $\texttt{math}$ module.*)

We will use the following equation to determine the angle $\theta$ between $X$ and $Y$, as well as the $\texttt{DotProduct}$ and $\texttt{Magnitude}$ functions.

$$
\begin{equation}
\cos{\theta} = \frac{X\cdot Y}{||X||||Y||}
\end{equation}
$$

In [8]:
X = np.array([[3],[-1],[2]])
Y = np.array([[4],[2],[0]])
print(math.acos((lag.DotProduct(X,Y))/((lag.Magnitude(X))*(lag.Magnitude(Y)))))

0.9302740141154721


$(b)$ Find a vector in $\mathbb{R}^3$ that is orthogonal to the vector $X$.  Verify your answer with a computation.

Two vectors are **orthogonal** if their dot product is zero. The vector $W$ defined below is an example of a vector that is orthogonal to $X$.

$$
\begin{equation}
W = \left[ \begin{array}{r} 1 \\ 3 \\ 0  \end{array}\right] 
\end{equation}
$$

In [38]:
X = np.array([[3],[-1],[2]])
W = np.array([[1],[3],[0]])
print(lag.DotProduct(X,W))

0.0


$(c)$ Construct a unit vector $Z$ such that $Z\cdot Y = -||Y||$.  Verify your answer with a computation.

First we calculate $-||Y|| = -\sqrt{4^2 + 2^2 + 0^2} = -2\sqrt{5}$. If we define the arbitrary vector $Z$ as below, then we see that we need to find values for $z_1, z_2$, and $z_3$ such that $||Z|| = \sqrt{(z_1)^2 + (z_2)^2 + (z_3)^2} = 1$ and $Z \cdot Y = 4z_1 + 2z_2 + 0z_3 = -2\sqrt{5}$.

$$
\begin{equation}
Z = \left[ \begin{array}{r} z_1 \\ z_2 \\ z_3  \end{array}\right] 
\end{equation}
$$

Since $z_3$ contributes nothing to the second sum above, lets set $z_3 = 0$ for simplicities sake. This gives a system of two equations in two unknowns, namely

$$
\begin{eqnarray*}
4z_1 + 2z_2 & = & -2\sqrt{5} \\
z_1^2 + z_2^2 & = & 1 \\
\end{eqnarray*}
$$

Note that we can't solve this system using elimination because the second equation is not linear.  Instead, if we solve for one of the variables in the first equation and substitute into the second, we will be able to use the quadratic formula to find a solution. Solving for $z_2$ in the first equation, we get

$$
\begin{eqnarray*}
z_2 & = & -\sqrt{5} - 2z_1 \\
\end{eqnarray*}
$$

Next we substitute this equality in for $z_2$ in our second equation, multiply out and move everything to the left.

$$
\begin{eqnarray*}
5z_1^2 + 4\sqrt{5}z_1 + 4 = 0 \\
\end{eqnarray*}
$$

Using the quadratic formula reveals that the two roots of this equation are equal, namely $z_1 = -\frac{2}{5}\sqrt{5}$. If we substitute this into the equation above where we had solved for $z_2$, we see that $z_2 = -\frac{1}{5}\sqrt{5}$ and thus the vector $Z$ below is a solution to our problem.

$$
\begin{equation}
Z = \left[ \begin{array}{r} -\frac{2\sqrt{5}}{5} \\ -\frac{\sqrt{5}}{5} \\ 0  \end{array}\right] 
\end{equation}
$$

In [47]:
Y = np.array([[4],[2],[0]])
Z = np.array([[-2*np.sqrt(5)/5],[-np.sqrt(5)/5],[0]])
print(lag.DotProduct(Z,Y),'\n')
print(-lag.Magnitude(Y),'\n')
print(lag.Magnitude(Z))

-4.47213595499958 

-4.47213595499958 

1.0
