## Introduction to Jupyter and Python

The purpose of this section is to provide enough instruction on the use of Jupyter and Python to successfully navigate and engage with the LA Guide.  There are vast resources available online for those that wish to learn more about these topics.  Some references are supplied at the end of the section. [Python](https://www.python.org/) is a very popular computer language for a wide range of applications, including scientific computing, and is known for being a language that is easy to learn for novice programers.  [Jupyter](https://jupyter.org/) is a web application that allows users to create and share documents called notebooks.  Jupyter notebooks can contain text, equations, and graphics, as well as live Python code with which the user can interact.  

### Cells 

This LA Guide is made up of a number of Jupyter notebooks.  Each notebook consists of a number of cells.  Every cell is either a **markdown cell**, or a **code cell**.  The markdown cells mostly contain text and [LaTex] instructions.  When executed, these cells generate the all of the formatted text and formulas that you see as you read through the guide.  The code cells contain instructions, written in Python, to be executed by the notebook.  Code cells will not produce much visual output to the notebook unless they contain instructions to do so.    

All cells in the notebooks, markdown and code, must be executed in order to produce output and results.  To execute a cell, select the cell and press 'Shift + Enter'.  You can select a cell by clicking it, or by moving up/down with the arrow keys.  In order to fully engage with the notebooks, you will also want to edit cells to change the outputs.  To change a cell you will have to enter **edit mode**.  When not in edit mode, the notebook is said to be in **command mode**.  

**Important: Your keyboard will do different things depending on the mode.**  

Let's see how to change modes right now, in this very cell.  When a cell is selected, there will be a colored bar on the left border of the cell.  The bar will be green in edit mode and blue in command mode.  To enter command mode we press 'Enter'.  To exit command mode without executing the cell we press 'Esc'.  To execute the cell press 'Shift + Enter'.  

Try it!  Edit the line below to include your name.

This copy of LA Guide belongs to ...



Although all cells can be edited and executed, there are some distinctions in the two types of cells.

- **All markdown cells are executed when you open the notebook, but code cells are not**.  This means that when you first open a notebook, the formatted text and formulas produced by the markdown cells will be displayed.  Clicking on the markdown cells will not do anything other than select the cell, and pressing 'Shift + Enter' will not display anything new since the output is already displayed.  By contrast, **any output from the code cells will not be displayed until you run the cells**.
- If there is anything amiss in a markdown cell, the displayed text or formula may not look right.  If there is anything amiss in the code cell, an error will be displayed.  These errors might be difficult to decipher at first, but with a little practice you will soon be able to understand the common errors that arise.



### Common Python tasks

#### Calculations, variable assignments, and printing

The first thing we might try is the use of code cells as a calculator.  Indeed this works in a straightforward way.  Run the cell below to see how it works.  Experiment with the input to see how to enter various operations.  (Note that you can get exponents by using the \*\* operator.)  

In [1]:
42*1.7

71.39999999999999


The next thing to learn is how to assign names to numbers and other objects.  For this task we use a command like $\texttt{b=32/5}$.  This code computes the value of $\texttt{32/5}$, then stores the result in a variable named $\texttt{b}$.

In [2]:
b = 32/5

Since the result was stored, the actual value of $\texttt{b}$ is not displayed as ouput from the code cell.  Indeed, nothing is displayed when the cell is executed.  Typically, when we want to display the results of a computation, we have to use a command called $\texttt{print}$.

In [2]:
b=32/5
print(b)

6.4


Often we will want to print text along with numerical results.  The text to be printed must be placed in quotes.  It is also possible to provide multiple items to the $\texttt{print}$ command by separating them with commas.

In [3]:
print("The calculation is complete.")
print("The result of the calculation 32/5 is ",b)

The calculation is complete.
The result of the calculation 32/5 is  6.4


The text within the quotes is a Python object known as a string.  We could assign the string a name as well if we plan to reuse it.  Python offers many powerful ways to manipulate and process strings, but we will only be using strings to display informative messages about our numerical results.  

In [9]:
result_message = "The result of the calculation is "
print(result_message,b)
print(result_message,b*37)

The result of the calculation is  6.4
The result of the calculation is  236.8


#### Functions

Quite often we write a bit of code that we would like to reuse.  Maybe it was tricky to figure out, or just tedious to type, and we want to save time and effort by making use of the code we've already written.  We could just copy and paste code from here to there, but that quickly becomes a chore too as the amount of code we write grows.  

One simple way to reuse code is to define a **function**.  We can think of a function as a new command that will carry out whatever instructions we put inside it.  Sometimes we will find it useful to provide the function with information in order for it to do its job.  Other times we might ask that the function return some information to us when it has finished its job.  Let's look at a couple of examples.

In the first example, we won't exchange information with the function, we will just ask it to display a message.  To define a function we use the command $\texttt{def}$.  We then list any instructions that we want the function to carry out.  The $\texttt{def}$ command must end with a colon (:), and the instructions that are part of the function **must be indented** with a 'Tab' key. 

In [12]:
def InchConversionFactor():
    print("There are 2.54 centimeters in 1 inch.")

Note that when we execute the cell, the message is not printed.  This statement only defines the function.  In order to execute the commands in the function, we have to call it.

In [14]:
InchConversionFactor()

There are 2.54 centimeters in 1 inch.


When we call the function, we need to include the parentheses () as part of the call.  In this example the parentheses are empty because we are not passing any information to the function.  Let's write another function that allows us to provide it with a measurement in inches, and have it print out the measurement in centimeters.

In [22]:
def cm_to_in_conversion(inches):
    cm = inches*2.54
    print("There are",cm,"centimeters in",inches,"inches.")  

Again, nothing actually happens until we call the function.  This time when we call though, we will need to provide a numer that the function will interpret as the variable $\texttt{inches}$.  The objects that we pass into functions are known as **arguments**.

In [23]:
cm_to_in_conversion(2.3)

There are 5.842 centimeters in 2.3 inches.


Finally, the last example we provide will the function with the measurement in centimeters, and it will *return to us* the measurement in centimeters without printing anything.

In [18]:
def return_cm_to_in_conversion(inches):
    cm = inches*2.54
    return cm

And again we must call the function to carry out the code.


In [21]:
result = return_cm_to_in_conversion(2.3)
print("Our result is",result)

Our result is 5.842


#### Conditional statements

Explain $\texttt{if}$ and $\texttt{else}$.  Give example 

#### Iterations

Brief and limitted explanation of $\texttt{for}$ and $\texttt{while}$.  Give relevant example.

#### Comments

Often it is useful to include some plain text inside the code cell to help provide a description or explanation.  Such text is called a comment.  Comments are not interpreted by Python, so we can write anything we like to help us document the code.  There are two ways to accomplish this.

1. Any portion of a line that follows the $\texttt{#}$ symbol is ignored by the interpretor.


In [4]:
a = 142
c = a**2  # c is the square of a
print("The square of",a,"is",c)

The square of 142 is 20164


2. Any portion of the code cell within triple quotes is ignored.

In [5]:
''' 
We can write 
several lines
worth of comments to explain
the purpose of the code
'''
a = 142
c = a**2  # c is the square of a
print("The square of",a,"is",c)

The square of 142 is 20164


The important point here is that the previous two cells do exactly the same thing.  The comments have no effect on the calculation or the output.  The following cell with no comments does exactly the same thing as well.

In [6]:
a = 142
c = a**2
print("The square of",a,"is",c)

The square of 142 is 20164


#### Importing

The core of the Python language does not contain all the functionality that we will need for linear algebra.  In order to access more tools we will **import** some Python modules.  For example, some basic functions that you might find on a scientific calculator are not part of the Python language, but are included in the math module.  A simple way to import this module is with the code $\texttt{import math}$.  The cell below shows some examples of how we might use the module.

In [7]:
import math
s = math.sqrt(2)
print("The square root of 2 is approximately",s)
PI = math.pi
print("Pi is approximately", PI)
print("The cosine of pi/10 is approximately",math.cos(PI/10))

The square root of 2 is approximately 1.4142135623730951
Pi is approximately 3.141592653589793
The cosine of pi/10 is approximately 0.9510565162951535


Note that when we use the square root function, we actullay need to type $\texttt{math.sqrt}$ instead of just $\texttt{sqrt}$.  This is because the square root function actually lives in the math module, and is not in the basic set of Python commands.

#### NumPy

Almost every calculation that we do in linear algebra will involve working with arrays of numbers.  An array can be thought of as a collection of numbers arranged into rows and columns to form a rectangle, such as the example below, which has 2 rows and 4 columns.


$$
\begin{equation}
\left[ \begin{array}{rrrr} 5 & -1 & 1 & 0 \\ 4 & 3 & 12 & -6 \end{array}\right]
\end{equation}
$$

Although it is possible to represent arrays using the basic objects, we will make use of a package called NumPy to work with our arrays.  NumPy has a convenient way to represent arrays and has many built-in tools for processing them.  Let's dive right in and create some arrays.  Just as with the math module, we have to first import NumPy before we can use it.  This time we will use the code $\texttt{import numpy as np}$, which imports the module but gives it a different name that is a little more convenient to type. 

The easiest way to create the array above is to use the $\texttt{array}$ function, and provide it a list of all the array entries specific format.  The row entries are separated by commas and enclosed in square brackets \[\], then all the rows listed together, separated by commas, and enclosed in another set of square brackets.   

In [5]:
import numpy as np

A = np.array([[5, -1, 1, 0],[4, 3, 12, -6]])
print(A)

[[ 5 -1  1  0]
 [ 4  3 12 -6]]


Another way to create the array we want is to first make an array that is one long row, and then use the $\texttt{reshape}$ function. 

In [10]:
B = np.array([5, -1, 1, 0, 4, 3, 12, -6])
print("This is B before reshaping.")
print(B)

C = B.reshape((2,4))
print("This is C, which is the entries of B formed into a new shape.")
print(C)

This is B before reshaping.
[ 5 -1  1  0  4  3 12 -6]
This is C, which is the entries of B formed into a new shape.
[[ 5 -1  1  0]
 [ 4  3 12 -6]]


### Common Python error messages

One typical error is something called a **Name Error**.  This error gets displayed when Python doesn't recognize a command or variable in the code.  Run the following cell to see an example.

In [8]:
result = 128*17
print(resutl)

NameError: name 'resutl' is not defined

We made a typo in the name of the variable name and the Python interpreter doesn't reconize the variable it is instructed to print.  This same error will arise if you try to use the $\texttt{result}$ in another calculation.


In [ ]:
result = 128*17
next_result = resutl / 10

There are other common ways to receive the Name Error.

1. If we begin working on a notebook somewhere in the middle, then that means all of the code cells at the start did not get executed.  If one of the cells we are working on references a variable from an earlier cell, we will get the Name Error.
2. If we try to use function from a module, but forget to actually import the module, we will get the Name Error.