## Linear Ranks

In [376]:
import numpy as np
from numpy.linalg import matrix_rank
import laguide as lag
from IPython.display import clear_output


A = np.random.randint(-10,11,size=(5,5))
iter = 1
while(matrix_rank(A) > 4):
    #print("A=\n",A)

    #print(lag.FullRowReduction(A_augmented))
    A = np.random.randint(-10,11,size=(5,5))
    clear_output()
    print(iter)
    iter += 1
print("A=\n",A)    

Z = np.zeros((A.shape[0],1))
A_augmented = np.append(A,Z,axis=1)
print(A_augmented)
print(lag.FullRowReduction(A_augmented))    

print(matrix_rank(A))

6678


KeyboardInterrupt: 

In [356]:
B = np.array([[0,-3],[-3,1],[3,2]])
Z = np.zeros((B.shape[0],1))

B_augmented = np.append(B,Z,axis=1)
print(lag.FullRowReduction(B_augmented))
print(matrix_rank(B))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
2


In [313]:
print("A=\n",A)

A=
 [[  5   5  -1   4]
 [-10  -9  -1  -9]
 [  1   4  10   5]
 [  7   8  10  10]]


In [352]:
from IPython.display import clear_output

print(2)
clear_output(wait=True)
print(3)

3
