## Linear Independence

A set of vectors $\{V_1, V_2, V_3, ... V_n\}$ is said to be **linearly independent** if no linear combination of the vectors is equal to zero, except the combination with all weights equal to zero.  Thus if the set is linearly independent and 

$$
\begin{equation}
c_1V_1 + c_2V_2 + c_3V_3 + .... + c_nV_n = 0
\end{equation}
$$

it must be that $c_1 = c_2 = c_3 = .... = c_n = 0$.  Equivalently we could say that the set of vectors is linearly independent if *there is no vector* in the set that is equal to a linear combination of the others.  If a set of vectors is not linearly independent, then we say that it is **linearly dependent**.


### Example 1

$$
\begin{equation}
V_1 = \left[ \begin{array}{r} 2 \\ 1 \end{array}\right] \hspace{1cm} 
V_2 = \left[ \begin{array}{r} 1 \\ -6  \end{array}\right] \hspace{1cm}
\end{equation}
$$

In order to determine if this set of vectors is linearly independent, we must examine the following vector equation.

$$
\begin{equation}
c_1\left[ \begin{array}{r} 2 \\ 1 \end{array}\right] +
c_2\left[ \begin{array}{r} 1 \\ -6  \end{array}\right] =
\left[ \begin{array}{r} 0 \\ 0 \end{array}\right]\end{equation}
$$



In [3]:
import numpy as np
import laguide as lag

A_augmented = np.array([[2,1,0],[1,-6,0]])
print(lag.FullRowReduction(A_augmented))

[[ 1.  0.  0.]
 [-0.  1. -0.]]


We see from the reduced augmented matrix that the only solution to the equation is $c_1 = c_2 = 0$.  The set $\{V_1, V_2\}$ is linearly independent.

### Example 2

$$
\begin{equation}
W_1 = \left[ \begin{array}{r} 2 \\ -1  \\ 1 \end{array}\right] \hspace{1cm} 
W_2 = \left[ \begin{array}{r} 1 \\ -4 \\ 0  \end{array}\right] \hspace{1cm}
W_2 = \left[ \begin{array}{r} 3 \\ 2 \\ 2  \end{array}\right] \hspace{1cm}
\end{equation}
$$

Again, we must examine the the solution to a vector equation.

$$
\begin{equation}
c_1\left[ \begin{array}{r} 2 \\ -1 \\ 1 \end{array}\right] +
c_2\left[ \begin{array}{r} 1 \\ -4 \\ 0  \end{array}\right] +
c_3\left[ \begin{array}{r} 3 \\ 2 \\ 2  \end{array}\right] =
\left[ \begin{array}{r} 0 \\ 0 \\ 0\end{array}\right]\end{equation}
$$


In [4]:
B_augmented = np.array([[2,1,3,0],[-1,-4,2,0],[1,0,2,0]])
print(lag.FullRowReduction(B_augmented))

[[ 1.  0.  2.  0.]
 [-0.  1. -1. -0.]
 [ 0.  0.  0.  0.]]


In this case we see that $c_3$ is a free variable.  If we set $c_3 = 1$, then $c_2 = 1$, and $c_1 = -2$.  Since we are able to find a solution other than $c_1 = c_2 = c_3 = 0$, the set of vectors $\{W_1, W_2, W_3\}$ is linearly dependent.

### Homogeneous systems

A linear system is said to be **homogeneous** if it can be described with the matrix equation $AX = 0$.  The solution to such a system has a connection to the solution of the system $AX=B$.  The homogenous system also has a connnection to the concept of linear independence.  If we link all of these ideas together we will be able to gain information about the solution of the system $AX=B$, based on some information about linear independence.

In the previous examples we were solving the vector equation $c_1V_1 + c_2V_2 + c_3V_3 + .... + c_nV_n = 0$ in order
to determine if the set of vectors $\{V_1, V_2, V_3 .... V_n\}$ were linearly independent.  This vector equation represents a homogenous linear system that could also be described as $AX=0$, where $V_1$, $V_2$, ... $V_n$ are the columns of the matrix $A$, and $X$ is the vector of unknown coefficients.  The set of vectors is linearly independent if and only if the associated homogeneous system has a solution other than the vector with all entries equal to zero.  The vector of all zeros is called the **trivial solution**.  This zero vector is called a trivial solution because it is a solution to *every homogeneous system* $AX=0$, regardless of the entries of $A$.  For this reason, we are interested only in the existence of *nontrivial solutions* to $AX=0$.

Furthermore, since these systems are linear, any single nontrivial solution implies the existence of an infinite number of nontrivial solutions.

Let us suppose that a homogeneous system $AX=0$ has a nontrivial solution (<font color=red> or go right to example </font>), which we could label $X_h$.  Let us also suppose that a related nonhomogeneous $AX=B$ also has some particular solution, which we could label $X_p$.  So we have $AX_h = 0$ and $AX_p = B$.  Now by the properties of matrix multiplication, $X_p + X_h$ is also a solution to $AX=B$ since $A(X_p + X_h) = AX_p + AX_h = B + 0$.  