## Linear Ranks

### From Zico Kolter, Linear Algebra Review and Reference.

> The **column rank** of a matrix $A \in \mathbb{R}^{m×n}$ is the size of the largest subset of columns of A that constitute a linearly independent set. With some abuse of terminology, this is often referred to simply as the number of linearly independent columns of A.[1] 

> In the same way, the **row rank** is the largest number of rows of A that constitute a linearly independent set.[1]

For any matrix $A \in \mathbb{R}^{m×n}$ , it turns out that the column rank of A is equal to the row rank of A (though we will not prove this), and so both quantities are referred to collectively as the rank of A, denoted as $rank(A)$. The following are some basic properties of the rank[1]:

1. For $A \in \mathbb{R}^{m×n}$ , $rank(A) \le min(m, n)$. If $rank(A) = min(m, n)$, then $A$ is said to be full rank .
2. For $A \in \mathbb{R}^{m×n}$ , $rank(A) = rank(A^T )$.
3. For $A \in \mathbb{R}^{m×n}$ , $B \in \mathbb{R}^{m×n}$ , $rank(AB) \le min(rank(A), rank(B))$.
4. For $A,B \in \mathbb{R}^{m×n}$ , $rank(A + B) \le rank(A) + rank(B)$.[1]

### From Linear algebra and its applications / David C. Lay

> <span style="color: red;">Def. </span>
The dimension of a nonzero subspace $H$ , denoted by $dim H$ , is the number of
vectors in any basis for $H$ . The dimension of the zero subspace $\{\textbf{0}\}$ is defined to be zero.$^1$ 

> <span style="color: red;">Def. </span> The **rank** of a matrix $A$ , denoted by $rank A$ , is the dimension of the column space of $A$ . Since the pivot columns of $A$ form a basis for $Col A$ , the rank of $A$ is just the number of pivot columns in $A$ .

> <span style="color: red;">Def. </span> **full rank** (matrix): An $m\times n$ matrix whose rank is $min(m,n)$.
 
$^1$ The zero subspace has no basis (because the zero vector by itself forms a linearly dependent set)

For finding matrix Rank we will use [function linalg.matrix_rank](https://numpy.org/doc/stable/reference/generated/numpy.linalg.matrix_rank.html), that's using [SVD method](https://en.wikipedia.org/wiki/Singular_value_decomposition) to decompose a matrix into several component matrices.

### Example 1:  Matrix in $\mathbb{R}^{4×5}$

$$ A = \left[ \begin{array}{r} 2 & 5 & -3 & -4 & 8 \\ 4 & 7 & -4 & -3 & 9 \\
                               6 & 9 & -5 & 2 & 4 \\ 0 & -9 & 6 & 5 & -6 \end{array}\right] \hspace{1cm} $$
Reduce A to RREF form:

In [4]:
import numpy as np
from numpy.linalg import matrix_rank
import laguide as lag
from IPython.display import clear_output

A = np.array([[2,5,-3,-4,8],[4,7,-4,-3,9],[6,9,-5,2,4],[0,-9,6,5,-6]])
A_reduced = lag.FullRowReduction(A)
print(A_reduced)
print("matrix_rank(A)=",matrix_rank(A))

[[ 1.          0.          0.16666667  0.          1.41666667]
 [ 0.          1.         -0.66666667  0.         -0.16666667]
 [ 0.          0.          0.          1.         -1.5       ]
 [ 0.          0.          0.          0.          0.        ]]
matrix_rank(A)= 3


The matrix $A$ has 3 pivot columns, so $rankA = 3$ . And as we see rank defined by function matrix_rank match with our definition.

The row reduction in Example 1 reveals that there are two free variables in $A \times \mathbf{x}= 0$, because two of the five columns of $A$ are not pivot columns. (The nonpivot columns correspond to the free variables in $A \times \mathbf{x}= 0$.) Since the number of pivot columns plus the number of nonpivot columns is exactly the number of columns, the dimensions of $Col A$ and $\mathcal{N} A$ have the following useful connection.[2]

> <span style="color: red;">Def. **The Rank Theorem**</span> 
 If a matrix A has n columns, then $rank A + dim( \mathcal{N} (A)) = dim(ColA)$ .

### Example 2:  Matrix in $\mathbb{R}^{4×4}$

$$ A = \left[ \begin{array}{r} 6& -3&5&-4 \\ 1&-4&-4&-9 \\
                               -1&-8&-1&-8 \\ 2&6&-6&-2 \end{array}\right] \hspace{1cm} $$
Reduce A to RREF form:

In [8]:
A = np.array([[ 6, -3,  5, -4],
 [ 1, -4, -4, -9],
 [-1, -8, -1 ,-8],
 [ 2,  6, -6, -2]])
A_reduced = lag.FullRowReduction(A)
print(A_reduced)
print("matrix_rank(A)=",matrix_rank(A))

[[ 1.  0.  0. -1.]
 [ 0.  1.  0.  1.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  0.  0.]]
matrix_rank(A)= 3


The matrix $A$ has 3 pivot columns, so $rankA = 3$ . And as we see rank defined by function matrix_rank match with our definition.

### Example 3:  Matrix in $\mathbb{R}^{3×3}$

$$ A = \left[ \begin{array}{r} 3&-2&1 \\ -7 &-2&2 \\ 4&-6 & -7
                                 \end{array}\right] \hspace{1cm} $$
Reduce A to RREF form:

In [ ]:
A= np.array(
 [[ 3, -2,  1],
 [-7, -2,  2],
 [ 4, -6, -7]])
A_reduced = lag.FullRowReduction(A)
print(A_reduced)
print("matrix_rank(A)=",matrix_rank(A))

The matrix $A$ has 3 pivot columns and it's match with matrix $dimA=3$, so $rankA = 3$ and matrix $A$ is a full rank matrix. And as we see rank defined by function matrix_rank match with our definition.

### Reference

1. Zico Kolter, Linear Algebra Review and Reference, October 7, 2008
2. Linear algebra and its applications / David C. Lay, University of Maryland, College Park, Steven R. Lay, Lee University, Judi J. McDonald, Washington State University. – Fifth edition.