## Introduction to NumPy and Matplotlib

Numpy is an essential Python package for carrying out the calculations needed for linear algebra as well as other areas of scientific computing.  Matplotlib is a extensive Python package for producing a wide variety of plots.  In this section we will demonstrate a few of the basic elements of these packages that will be used repeatedly throughout the Jupyter Guide to Linear Algebra.  

It should be noted that NumPy is used for many of the actual calculations encounted in linear algebra, while we use Matplotlib only to make useful visual representations of the concepts.  The use of NumPy therefore will be crucial, while the use of Matplotlib is not explicitly required to engage with the content of the guide.  The Matplotlib demonstration below also contains more complex details that might be difficult to digest until the reader gains some experience with Python.  For these reasons, The reader may choose to skip the introduction to Matplotlib and return at a later point if interest arises. 



### NumPy

Almost every calculation that we do in linear algebra will involve working with arrays of numbers.  An array can be thought of as a collection of numbers arranged into rows and columns to form a rectangle, such as the example below, which has 2 rows and 4 columns.


$$
\begin{equation}
\left[ \begin{array}{rrrr} 5 & -1 & 1 & 0 \\ 4 & 3 & 12 & -6 \end{array}\right]
\end{equation}
$$

Although it is possible to represent arrays using the basic objects, we will make use of a package called NumPy to work with our arrays.  NumPy has a convenient way to represent arrays and has many built-in tools for processing them.  Let's dive right in and create some arrays.  Just as with the math module, we have to first import NumPy before we can use it.  This time we will use the code $\texttt{import numpy as np}$, which imports the module but gives it a different name that is a little more convenient to type. 

The easiest way to create the array above is to use the $\texttt{array}$ function, and provide it a list of all the array entries specific format.  The row entries are separated by commas and enclosed in square brackets \[\], then all the rows listed together, separated by commas, and enclosed in another set of square brackets.   

In [1]:
import numpy as np

A = np.array([[5, -1, 1, 0],[4, 3, 12, -6]])
print(A)

[[ 5 -1  1  0]
 [ 4  3 12 -6]]


Another way to create the array we want is to first make an array that is one long row, and then use the $\texttt{reshape}$ function. 

In [2]:
B = np.array([5, -1, 1, 0, 4, 3, 12, -6])
print("This is B before reshaping.")
print(B)

C = B.reshape((2,4))
print("This is C, which is the entries of B formed into a new shape.")
print(C)

This is B before reshaping.
[ 5 -1  1  0  4  3 12 -6]
This is C, which is the entries of B formed into a new shape.
[[ 5 -1  1  0]
 [ 4  3 12 -6]]


We will often wish to make modifications to an array while keeping a copy of the original.  In this situation we can duplicate an existing array with the $\texttt{copy}$ function.

In [3]:
D = np.copy(A)
print(D)

[[ 5 -1  1  0]
 [ 4  3 12 -6]]


In order to access individual entries in an array, we need to use a pair of indices to refer to the row and column of the entry we are accessing.  As with almost every other computing language, the count begins at zero in Python!  This means that the first row has index 0, the second has index 1 and so forth.  The same is true for the columns.  Beginning the count at zero is not difficult, but it does require an adjustment in thinking if one is new to programming.  

In [4]:
print(A[0,2])

1


We can modify individual array values by assigning them new numbers.

In [5]:
A[0,2] = 8
print(A)

[[ 5 -1  8  0]
 [ 4  3 12 -6]]


Many of the functions included in NumPy relate to linear algebra in some way.  We will demonstrate more of these functions as we make our way through the corresponding linear algebra topics.



### Matplotlib