## Vector Spaces

In [3]:
import laguide as lag
import numpy as np
import scipy.linalg as sla

### General Linear Systems

**Exercise 1:** Determine the number of solutions to the following system, then find all possible solutions.


$$
\begin{eqnarray*}
5x_1 + 4x_2 - x_3 & = & \hspace{0.3cm} 3\\
x_1 \hspace{1.2cm} + x_3  & = & \hspace{0.3cm} 2\\
-2x_1 + 2x_2 + 4x_3 & = & -3 \\
x_1 + 8x_2 + 7x_3 & = & -3 \\
3x_1 \hspace{1.2cm} - 3x_3 & = & \hspace{0.3cm} 3 \\
\end{eqnarray*}
$$

In [4]:
A_augmented = np.array([[5,4,-1,3],[1,0,1,2],[-2,2,4,-3],[1,8,7,-3],[3,0,-3,3]])
A_augmented_reduced = lag.FullRowReduction(A_augmented)
print(A_augmented_reduced)

[[ 1.   0.   0.   1.5]
 [ 0.   1.   0.  -1. ]
 [ 0.   0.   1.   0.5]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]]


Every column except the last one has exactly one pivot, so there exists a unique solution to this system. That solution is

$$
\begin{eqnarray*}
x_1 & = & 1.5\\
x_2  & = & -1\\
x_3 & = & 0.5
\end{eqnarray*}
$$

**Exercise 2:** Determine the number of solutions to the following system, then find all possible solutions.


$$
\begin{eqnarray*}
5x_1 + 4x_2 - x_3 & = & \hspace{0.3cm} 0\\
x_1 \hspace{1.2cm} + x_3  & = & \hspace{0.3cm} 2\\
-2x_1 + 2x_2 + 4x_3 & = & -3 \\
x_1 + 8x_2 + 7x_3 & = & -3 \\
3x_1 \hspace{1.2cm} - 3x_3 & = & \hspace{0.3cm} 3 \\
\end{eqnarray*}
$$

In [5]:
## Code solution here.

**Exercise 3:** Determine the number of solutions to the following system, then find all possible solutions.

$$
\begin{eqnarray*}
5x_1 + 4x_2 - x_3 & = & \hspace{0.3cm} 3\\
x_1  +2x_2 + x_3  & = & \hspace{0.3cm} 0\\
-2x_1 + 2x_2 + 4x_3 & = & -3 \\
x_1 + 8x_2 + 7x_3 & = & -3 \\
3x_1 \hspace{1.2cm} - 3x_3 & = & \hspace{0.3cm} 3 \\
\end{eqnarray*}
$$

In [6]:
B_augmented = np.array([[5,4,-1,3],[1,2,1,0],[-2,2,4,-3],[1,8,7,-3],[3,0,-3,3]])
B_augmented_reduced = lag.FullRowReduction(B_augmented)
print(B_augmented_reduced)

[[ 1.   0.  -1.   1. ]
 [ 0.   1.   1.  -0.5]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]]


Niether the third nor the last column have pivots, so there exist an infinite number of solutions to this system. If we parametrize $x_3 = s$ then the following is a solution to the system for any $s \in \mathbb{R}$

$$
\begin{eqnarray*}
x_1 & = & 1 + s\\
x_2  & = & -0.5 - s\\
x_3 & = & s
\end{eqnarray*}
$$

**Exercise 4:** Construct an example of an inconsistent system with 2 equations and 4 unknowns.  Check your example by using $\texttt{FullRowReduction}$

$$
\begin{eqnarray*}
2x_1 + 4x_2 - 3x_3 & = & \hspace{0.3cm} 3\\
4x_1 + 8x_2 - 6x_3 & = & \hspace{0.3cm} 5\\
\end{eqnarray*}
$$

In [7]:
C_augmented = np.array([[2,4,-3,3],[4,8,-6,5]])
C_augmented_reduced = lag.FullRowReduction(C_augmented)
print(C_augmented,'\n')
print(C_augmented_reduced)

[[ 2  4 -3  3]
 [ 4  8 -6  5]] 

[[ 1.   2.  -1.5  0. ]
 [ 0.   0.   0.   1. ]]


The scond row in the augmented matrix represents the equation $0x_3 = 1$.

**Exercise 5:** Explain why it is not possible for a system with 2 equations and 4 unknowns to have a unique solution.  Base your argument on pivot positions.

The augmented matrix that represents a system with 2 equations and 4 unknowns must can have at most 2 pivots since it has only 2 rows.  This means that one of the first four columns does not have a pivot and corresponds to a free variable in the system.  The guaranteed existence of a free variable means the system does not have a unique solution.

**Exercise 6:** Write a function that accepts the augmented matrix for a system and returns the number of free variables in that system.  Make use of $\texttt{FullRowReduction}$ in the $\texttt{laguide}$ module. 

In [8]:
## Code solution here.

### Linear Combinations

**Exercise 1:**  Find a linear combination of the vectors $V_1, V_2$ and $V_3$ which equals to the vector $X$.

$$
\begin{equation}
V_1 = \left[ \begin{array}{r} 2 \\ 0 \\ 7 \end{array}\right] \hspace{1cm}
V_2 = \left[ \begin{array}{r} 2 \\ 4 \\ 5   \end{array}\right] \hspace{1cm} 
V_3 = \left[ \begin{array}{r} 2 \\ -12 \\ 13 \end{array}\right] \hspace{1cm}
X = \left[ \begin{array}{r}  -1 \\ 5 \\ -6  \end{array}\right] \hspace{1cm}
\end{equation}
$$



In [6]:
## Code solution here.

**Exercise 2:**  Determine whether or not $X$ lies in the span of $\{ V_1, V_2 ,V_3\}$.

$$
\begin{equation}
V_1 = \left[ \begin{array}{r} 1 \\ 0 \\ 0 \end{array}\right] \hspace{1cm}
V_2 = \left[ \begin{array}{r} 2 \\ -2 \\ 1  \end{array}\right] \hspace{1cm} 
V_3 = \left[ \begin{array}{r} 2 \\ 0 \\ 4 \end{array}\right] \hspace{1cm}
X = \left[ \begin{array}{r}  1 \\ 3 \\ -1  \end{array}\right] \hspace{1cm}
\end{equation}
$$



In [6]:
## Code solution here.

**Exercise 3:**  Does the set $\{ X_1, X_2 ,X_3, X_4\}$ span $\mathbb{R}^4$? Explain why or why not.

$$
\begin{equation}
X_1 = \left[ \begin{array}{r} 1 \\ 1\\ 1\\1 \end{array}\right] \hspace{1cm}
X_2 = \left[ \begin{array}{r} 1 \\ 0 \\ 0\\2  \end{array}\right] \hspace{1cm} 
X_3 = \left[ \begin{array}{r} 2 \\ 0 \\ 1\\1 \end{array}\right] \hspace{1cm}
X_4 = \left[ \begin{array}{r} 3 \\ 0 \\ 1\\2 \end{array}\right] \hspace{1cm}
\end{equation}
$$



In [6]:
## Code solution here.

**Exercise 4:** Answer questions regarding the following vectors.

$$
\begin{equation}
W_1 = \left[ \begin{array}{r} 2 \\ 3 \\ -1 \end{array}\right] \hspace{1cm}
W_2 = \left[ \begin{array}{r} 3 \\ 0 \\ 1   \end{array}\right] \hspace{1cm} 
W_3 = \left[ \begin{array}{r} 4 \\ -3 \\ 3 \end{array}\right] \hspace{1cm}
B = \left[ \begin{array}{r}  1 \\ 1 \\ 1  \end{array}\right] \hspace{1cm}
C = \left[ \begin{array}{r}  3 \\ 0 \\ 1  \end{array}\right] \hspace{1cm}
V_1 = \left[ \begin{array}{r} 8 \\ -3 \\ 5 \end{array}\right] \hspace{1cm}
V_2 = \left[ \begin{array}{r} 4 \\ 6 \\ -2   \end{array}\right]  
\end{equation}
$$

$(a)$ Determine if $B$ is in the span of $\{W_1, W_2, W_3\}$.

We need to determine if there are scalars $a_1$, $a_2$, $a_3$ such that $a_1W_1 + a_2W_2 + a_3W_3 = B$.  We build an augmented matrix that represents the corresponding linear system and then use $\texttt{FullRowReduction}$.

In [9]:
B_augmented = np.array([[2,3,4,1],[3,0,-3,1],[-1,1,3,1]])
B_augmented_reduced = lag.FullRowReduction(B_augmented)
print(B_augmented,'\n')
print(B_augmented_reduced)

[[ 2  3  4  1]
 [ 3  0 -3  1]
 [-1  1  3  1]] 

[[ 1.  0. -1.  0.]
 [ 0.  1.  2.  0.]
 [ 0.  0.  0.  1.]]


This augmented matrix has a pivot in the last column.  Therefore the system is inconsistent and $B$ is not  in the span of $\{W_1, W_2, W_3\}$.

$(b)$ Determine if $C$ is in the span of $\{W_1, W_2, W_3\}$.

We need to determine if there are scalars $a_1$, $a_2$, $a_3$ such that $a_1W_1 + a_2W_2 + a_3W_3 = C$.  We build an augmented matrix that represents the corresponding linear system and then use $\texttt{FullRowReduction}$.

In [10]:
C_augmented = np.array([[2,3,4,3],[3,0,-3,0],[-1,1,3,1]])
C_augmented_reduced = lag.FullRowReduction(C_augmented)
print(C_augmented,'\n')
print(C_augmented_reduced)

[[ 2  3  4  3]
 [ 3  0 -3  0]
 [-1  1  3  1]] 

[[ 1.  0. -1.  0.]
 [ 0.  1.  2.  1.]
 [ 0.  0.  0.  0.]]


Since there is no pivot in the last column, the system is consistent and $C$ is in the span of $\{W_1, W_2, W_3\}$.

$(c)$ Find a nonzero vector in the span of $\{W_1, W_2, W_3\}$ that has zero as its first entry.

Any linear combination of $W_1$, $W_2$, and $W_3$ is in the span of $\{W_1, W_2, W_3\}$.  There are many that have zero as the first entry, including the following example.

$$
\begin{equation}
-2W_1 + W_3 = \left[ \begin{array}{r} -4 \\ -6 \\ 2 \end{array}\right] + \left[ \begin{array}{r} 4 \\ -3 \\ 1 \end{array}\right] = \left[ \begin{array}{r} 0 \\ -9 \\ 3 \end{array}\right] \hspace{1cm}
\end{equation}
$$

$(d)$ How can we determine if the span of $\{W_1, W_2, W_3\}$ equal the span of $\{V_1, V_2\}$?

If each of the vectors in $\{V_1, V_2\}$ is in the span of $\{W_1, W_2, W_3\}$ and vice versa, then the two sets should have the same span. However, we can quickly show that $V_1$ is not in the span of $\{W_1, W_2, W_3\}$.

In [11]:
V_1_augmented = np.array([[2,3,4,8],[3,0,-3,-3],[-1,1,3,5]])
V_1_augmented_reduced = lag.FullRowReduction(V_1_augmented)
print(V_1_augmented,'\n')
print(V_1_augmented_reduced)

[[ 2  3  4  8]
 [ 3  0 -3 -3]
 [-1  1  3  5]] 

[[ 1.  0. -1.  0.]
 [ 0.  1.  2.  0.]
 [ 0.  0.  0.  1.]]


Since the last column has a pivot this system is inconsistent. Therefore $V_1$ is not in the span of $\{W_1, W_2, W_3\}$ and thus the two sets have different spans.

**Exercise 5:** Show that the vector $X$ lies in the span of the columns of $A$. Also find another vector that is in the span of the columns of $A$ and verify your answer.

$$
\begin{equation}
A = \left[ \begin{array}{rrrr} 
1 & 1 & 3  \\ 2 & 0 & 1   \\ 3 & 1 & 1     
\end{array}\right] \hspace{2 cm}
x = \left[ \begin{array}{r} 1 \\ 1\\ 1 \end{array}\right] \hspace{1cm}
\end{equation}
$$



**Exercise 6:** Consider the matrix $R$ from **Example 3**.  Find one vector in $\mathbb{R}^4$ that is in the span of the columns of $R$, and one vector in $\mathbb{R}^4$ that is not.  Demontrate with an appropriate computation.


$$
\begin{equation}
R = \left[ \begin{array}{rrrr} 
1 & 1 & 0 & -1 \\ 1 & 1 & 0 & 1  \\ -1 & -1 & 1 & -1 \\ 1 & 1 & -2 & 0   
\end{array}\right]
\end{equation}
$$

Consider the following vectors $V$ and $W$. $V$ is not in the span of the columns of $R$, but $W$ is.

$$
\begin{equation}
V = \left[ \begin{array}{r} 0 \\ 0 \\ 0 \\ 1 \end{array}\right] \hspace{1cm}
W = \left[ \begin{array}{r} 0 \\ 2 \\ -2 \\ 1   \end{array}\right]
\end{equation}
$$

In [12]:
V_augmented = np.array([[1,1,0,-1,0],[1,1,0,1,0],[-1,-1,1,-1,0],[1,1,-2,0,1]])
V_augmented_reduced = lag.FullRowReduction(V_augmented)
print(V_augmented,'\n')
print(V_augmented_reduced,'\n')

W_augmented = np.array([[1,1,0,-1,0],[1,1,0,1,2],[-1,-1,1,-1,-2],[1,1,-2,0,1]])
W_augmented_reduced = lag.FullRowReduction(W_augmented)
print(W_augmented,'\n')
print(W_augmented_reduced)

[[ 1  1  0 -1  0]
 [ 1  1  0  1  0]
 [-1 -1  1 -1  0]
 [ 1  1 -2  0  1]] 

[[1. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

[[ 1  1  0 -1  0]
 [ 1  1  0  1  2]
 [-1 -1  1 -1 -2]
 [ 1  1 -2  0  1]] 

[[1. 1. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0.]]


Note that for any vector $X$ in $\mathbb{R}^4$, the vector $RX$ is a linear combination of the columns of $R$ and therefore in the span of the columns of $R$.

**Exercise 7:** Find a vector $V_3$ that is not in the span of $\{ V_1, V_2\}$. Explain why the set $\{ V_1, V_2, V_3 \}$ spans $\mathbb{R}^3$.

$$
\begin{equation}
V_1 = \left[ \begin{array}{r} 1 \\ 1\\ 1 \end{array}\right] \hspace{1cm}
V_2 = \left[ \begin{array}{r} 2 \\ 0 \\ 4  \end{array}\right] \hspace{1cm} 
\end{equation}
$$



In [10]:
## Code solution here.

**Exercise 8:** Explain why the system $AX=B$ cannot be consistent for every vector $B$ if $A$ is a $5\times 3$ matrix.

**Exercise 9:** Find the value of $a$ for which $\{ V_1, V_2 ,V_3\} $ does not span $\mathbb{R}^3$.

$$
\begin{equation}
V_1 = \left[ \begin{array}{r} 1 \\ 2\\ 3 \end{array}\right] \hspace{1cm}
V_2 = \left[ \begin{array}{r} 4 \\ 5 \\ 6  \end{array}\right] \hspace{1cm} 
V_3 = \left[ \begin{array}{r} 1 \\ 0 \\ a \end{array}\right] \hspace{1cm}
\end{equation}
$$




### Linear Independence

**Exercise 1:** Determine if the following set of vectors is linearly independent.

$$
\begin{equation}
U_1 = \left[ \begin{array}{r} 0 \\ 5  \\ 2  \\ 2 \end{array}\right] \hspace{1cm} 
U_2 = \left[ \begin{array}{r} 1 \\ -1 \\ 0  \\ -1 \end{array}\right] \hspace{1cm}
U_3 = \left[ \begin{array}{r} 3 \\ 2 \\ 2  \\ -1 \end{array}\right]
\end{equation}
$$

In [13]:
U = np.array([[0,1,3],[5,-1,2],[2,0,2],[2,-1,-1]])
U_reduced = lag.FullRowReduction(U)
print(U_reduced)

[[1. 0. 1.]
 [0. 1. 3.]
 [0. 0. 0.]
 [0. 0. 0.]]


The absence of a pivot in the third column indicates that these vectors are linearly dependent.

**Exercise 2:** Find two distinct nonzero vectors in the null space of the matrix $D$.

$$
\begin{equation}
D = \left[ \begin{array}{rrr} 4 & 4 & 3 \\ 8 & 8 & 6 \\ 1 & 0 & 1 \end{array}\right]
\end{equation}
$$

In [14]:
## Code solution here.

### Bases

**Exercise 1:** Find a basis for the set of solutions to the system $PX=0$ where $P$ is defined as follows.

$$
\begin{equation}
P = \left[ \begin{array}{rrrr} 1 & 0 & 3 & -2 & 4 \\ -1 & 1 & 6 & -2 & 1 \\ -2 & 1 & 3 & 0 & -3 \end{array}\right] 
\end{equation}
$$

In [15]:
P = np.array([[1,0,3,-2,4],[-1,1,6,-2,1],[-2,1,3,0,-3]])
P_reduced = lag.FullRowReduction(P)
print(P_reduced)

[[ 1.  0.  3. -2.  4.]
 [ 0.  1.  9. -4.  5.]
 [ 0.  0.  0.  0.  0.]]


In this system, $x_3$, $x_4$, and $x_5$ are free variables. If we parametrize them as $x_3 = r$, $x_4 = s$, and $x_5 = t$ then $x_1 = -3r + 2s - 4t$ and $x_2 = -9r + 4s - 5t.$ Then we can write the components of a general solution vector $X$ in terms of these parameters.

$$
\begin{equation}
X = \left[ \begin{array}{r} x_1 \\ x_ 2 \\ x_ 3 \\ x_4 \\ x_5 \end{array}\right] =  
r\left[ \begin{array}{r} -3 \\ -9 \\  1 \\ 0 \\ 0 \end{array}\right] +
s\left[ \begin{array}{r} 2 \\ 4 \\ 0 \\ 1 \\ 0 \end{array}\right] +
t\left[ \begin{array}{r} -4 \\ -5 \\ 0 \\ 0 \\ 1 \end{array}\right]
\end{equation}
$$

Therefore any solution to the system must be a linear combination of $V_1, V_2,$ and $V_3$ as defined below, and therefore $\{V_1,V_2,V_3\}$ forms a basis for the set of solutons to $PX = 0$.

$$
\begin{equation}
V_1 = \left[ \begin{array}{r} -3 \\ -9 \\  1 \\ 0 \\ 0 \end{array}\right] \hspace{1cm}
V_2 = \left[ \begin{array}{r} 2 \\ 4 \\ 0 \\ 1 \\ 0  \end{array}\right] \hspace{1cm}
V_3 = \left[ \begin{array}{r} -4 \\ -5 \\ 0 \\ 0 \\ 1  \end{array}\right]
\end{equation}
$$

**Exercise 2:** Determine if the following set of vectors is a basis for $\mathbb{R}^4$.  Give justification with an appropriate calculation.

$$
\begin{equation}
W_1 = \left[ \begin{array}{r} -1 \\ 0 \\ 1 \\ 2 \end{array}\right] \hspace{0.7cm} 
W_2 = \left[ \begin{array}{r} 2 \\ 1 \\ 2 \\ 4 \end{array}\right] \hspace{0.7cm}
W_3 = \left[ \begin{array}{r} 0 \\ 0 \\ 1 \\ 0 \end{array}\right] \hspace{0.7cm}
W_4 = \left[ \begin{array}{r} -1 \\ 0 \\ -1 \\ 1 \end{array}\right]
\end{equation}
$$

In [16]:
W = np.array([[-1,2,0,-1],[0,1,0,0],[1,2,1,-1],[2,4,0,1]])
W_reduced = lag.FullRowReduction(W)
print(W_reduced)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


We can see that the RREF of $W$ has a pivot in every row and column, and thus this set of vectors forms a basis for $\mathbb{R}^4$.

**Exercise 3:** Give an example of a set of three vectors that does **not** form a basis for $\mathbb{R}^3$.  Provide a calculation that shows why the example is not a basis.

Consider the set of vectors $\{V_1,V_2,V_3\}$ defined below.

$$
\begin{equation}
V_1 = \left[ \begin{array}{r} 1 \\ 0 \\ 0 \end{array}\right] \hspace{0.7cm} 
V_2 = \left[ \begin{array}{r} 0 \\ 1 \\ 0 \end{array}\right] \hspace{0.7cm}
V_3 = \left[ \begin{array}{r} 1 \\ 1 \\ 0 \end{array}\right] \hspace{0.7cm}
\end{equation}
$$

In [17]:
V_1 = np.array([[1],[0],[0]])
V_2 = np.array([[0],[1],[0]])
V_3 = np.array([[1],[1],[0]])
print(V_1 + V_2 - V_3)

[[0]
 [0]
 [0]]


Since we have found a non-trivial linear combination of the vectors that equals zero, the set is linearly dependent and therefore not a basis.

**Exercise 4:** Calculate the dimension of the span of the following vectors.

$$
\begin{equation}
U_1 = \left[ \begin{array}{r} 1 \\ 2 \\ -1 \\ 3 \end{array}\right] \hspace{0.7cm} 
U_2 = \left[ \begin{array}{r} 2 \\ -3 \\ 3 \\ -2 \end{array}\right] \hspace{0.7cm}
U_3 = \left[ \begin{array}{r} 3 \\ -1 \\ 2 \\ 1 \end{array}\right] \hspace{0.7cm}
U_4 = \left[ \begin{array}{r} 5 \\ -4 \\ 4 \\ -1 \end{array}\right]
\end{equation}
$$

In [18]:
## First we check to see if U_1 and U_2 are linearly independent

U_12 = np.array([[1,2],[2,-3],[-1,3],[3,-2]])
U_12_reduced = lag.FullRowReduction(U_12)
print(U_12_reduced)

[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]]


In [19]:
## They are linearly independent, so now we check if adding U_3 changes that

U_123 = np.array([[1,2,3],[2,-3,-1],[-1,3,2],[3,-2,1]])
U_123_reduced = lag.FullRowReduction(U_123)
print(U_123_reduced)

[[1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
## The last column does not have a pivot, so U_3 is included in the span of U_1 and U_2. Now we check U_4

U_124 = np.array([[1,2,5],[2,-3,-4],[-1,3,4],[3,-2,-1]])
U_124_reduced = lag.FullRowReduction(U_124)
print(U_124_reduced)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


$U_1$, $U_2$, and $U_4$ are linearly independent and $U_3$ can be expressed as a linear combination of the other three. Therefore the subspace of $\mathbb{R}^4$ spanned by $\{U_1,U_2,U_4\}$ is three-dimensional.