## Eigenvalues

In [1]:
import laguide as lag
import numpy as np
import scipy.linalg as sla
%matplotlib inline
import matplotlib.pyplot as plt
import math

**Exercise 1:** Determine the eigenvalues and corresponding eigenvectors of the following matrices by considering the transformations that they represent. Check your answers with a few computations.

$(a)$

$$
\begin{equation}
A = \left[ \begin{array}{cc} 1 & 0 \\ 0 & -3 \end{array}\right]
\end{equation}
$$

**Solution:**

Recall from [Chapter 4](Planar_Transformations.ipynb) that applying the transformation represented by $A$ is equivalent to stretching in the direction of the $y$-axis by a factor of 3 and then reflecting over the $y$-axis. If we imagine what this does to vectors in the plane then we might see that any vector that lies on the $x$-axis will be left unaffected. Therefore our first eigenvalue is $\lambda_1 = 1$ which corresponds to any scalar multiple of our first eigenvector $V_1 = \begin{equation} \left[ \begin{array}{cc} 1 \\ 0 \end{array}\right] \end{equation}$. Additionally, any vector that lies on the $y$-axis will simply be scaled by a factor of $-3$. Therefore our second eigenvalue is $\lambda_2 = -3$ which corresponds to any scalar multiple of our second eigenvector $V_2 = \begin{equation} \left[ \begin{array}{cc} 0 \\ 1 \end{array}\right] \end{equation}$.

In [5]:
A = np.array([[1,0],[0,-3]])
V1 = np.array([[1],[0]])
V2 = np.array([[0],[1]])
R = np.array([[5],[0]])
S = np.array([[1],[1]])
T = np.array([[0],[0]])

print(A@V1,'\n')
print(A@V2,'\n')
print(A@R,'\n')
print(A@S,'\n')
print(A@T)

[[1]
 [0]] 

[[ 0]
 [-3]] 

[[5]
 [0]] 

[[ 1]
 [-3]] 

[[0]
 [0]]


$(b)$

$$
\begin{equation}
B = \left[ \begin{array}{cc} 1 & 1 \\ 0 & 1 \end{array}\right]
\end{equation}
$$

**Solutions:**

Recall from [Chapter 4](Planar_Transformations.ipynb) that applying the transformation represented by $B$ is equivalent to shearing along the $x$-axis with a shearing factor of 1. Any vector that lies along the $x$-axis will be left unchanged because its $y$-coordinate is 0 and thus adds nothing to $x$-coordinate. Therefore our first eigenvalue is $\lambda_1 = 1$ which corresponds to any scalar multiple of our first eigenvector $V_1 = \begin{equation} \left[ \begin{array}{cc} 1 \\ 0 \end{array}\right] \end{equation}$. Any other vector with a nonzero $y$-coordinate will shear off of its original span, and thus cannot be a scalar multiple of itself. Therefore $V_1$ is the only eigenvalue of $B$.

In [6]:
B = np.array([[1,1],[0,1]])
V1 = np.array([[1],[0]])
V2 = np.array([[0],[1]])
R = np.array([[5],[0]])
S = np.array([[1],[1]])
T = np.array([[0],[0]])

print(B@V1,'\n')
print(B@V2,'\n')
print(B@R,'\n')
print(B@S,'\n')
print(B@T)

[[1]
 [0]] 

[[1]
 [1]] 

[[5]
 [0]] 

[[2]
 [1]] 

[[0]
 [0]]


$(c)$

$$
\begin{equation}
C = \left[ \begin{array}{cc} cos(\frac{\pi}{2}) & -sin(\frac{\pi}{2}) \\ sin(\frac{\pi}{2}) & cos(\frac{\pi}{2}) \end{array}\right]
\end{equation}
$$

**Solution:**

Recall from [Chapter 4](Planar_Transformations.ipynb) that applying the transformation represented by $C$ is equivalent to a rotation about the origin by the angle $\frac{\pi}{2}$. Any nonzero vector that is transformed by this matrix will be pointing directly perpendicular to its original direction, so cannot lie on its original span. Therefore $C$ has no eigenvalues nor any eigenvectors.

In [15]:
C = np.array([[math.cos(math.pi/2),-math.sin(math.pi/2)],[math.sin(math.pi/2),math.cos(math.pi/2)]])
V1 = np.array([[1],[0]])
V2 = np.array([[0],[1]])
R = np.array([[5],[0]])
S = np.array([[1],[1]])
T = np.array([[0],[0]])

print(np.round(C@V1),'\n')
print(np.round(C@V2),'\n')
print(np.round(C@R),'\n')
print(np.round(C@S),'\n')
print(np.round(C@T))

[[0.]
 [1.]] 

[[-1.]
 [ 0.]] 

[[0.]
 [5.]] 

[[-1.]
 [ 1.]] 

[[0.]
 [0.]]


$(d)$

$$
\begin{equation}
D = \left[ \begin{array}{cc} -0.6 & -0.8 \\ -0.8 & 0.6 \end{array}\right]
\end{equation}
$$

### Diagonalization

**Exercise 1:** Find the diagonalization of the matrix from **Example 1**.

$$
\begin{equation}
A = \left[ \begin{array}{rr} 2 & -1  \\ -1 & 2 \end{array}\right]
\end{equation}
$$

**Solution:** Recall that $A$ has eigenvalues $\lambda_1 = 3$ and $\lambda_2 = 1$, and corresponding eigenvectors $V_1$ and $V_2$ defined below.

$$
\begin{equation}
V_1 = \left[ \begin{array}{r} 1 \\ -1 \end{array}\right] \hspace{2cm} V_2 = \left[ \begin{array}{r} 1 \\ 1 \end{array}\right]
\end{equation}
$$

To find the diagonalization of $A$, we need to find the diagonal matrix $D$ with the eigenvalues of $A$ along its diagonal, and the matrix $S$ which has columns equal to the eigenvectors of $A$. We write them out below, and then verify that $A = SDS^{-1}$.

$$
\begin{equation}
D = \left[ \begin{array}{r} 3 & 0 \\ 0 & 1 \end{array}\right] \hspace{2cm} S = \left[ \begin{array}{r} 1 & 1 \\ -1 & 1 \end{array}\right]
\end{equation}
$$

In [3]:
A = np.array([[2,-1],[-1,2]])
D = np.array([[3,0],[0,1]])
S = np.array([[1,1],[-1,1]])
print(A - S@D@lag.Inverse(S))

[[0. 0.]
 [0. 0.]]


**Exercise 2:** Find the diagonalization of the following matrix.

$$
\begin{equation}
B = \left[ \begin{array}{rrr} 2 & 0 & 0  \\ 3 & -2 & 1 \\  1 & 0 & 1\end{array}\right]
\end{equation}
$$

**Solution:** First we must find the eigenvectors of $B$ and their corresponding eigenvalues. We make use of the $\texttt{eig}$ function to do this.

In [6]:
B = np.array([[2,0,0],[3,-2,1],[1,0,1]])
evalues,evectors = sla.eig(B)
print(evalues,'\n')
print(evectors)

[-2.+0.j  1.+0.j  2.+0.j] 

[[0.         0.         0.57735027]
 [1.         0.31622777 0.57735027]
 [0.         0.9486833  0.57735027]]


$S$ is equivalent to the matrix of eigenvectors above, so all we have to do is write out $D$ and then verify that $B = SDS^{-1}$.

In [7]:
D = np.array([[-2,0,0],[0,1,0],[0,0,2]])
S = evectors
print(B - S@D@lag.Inverse(S))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**Exercise 3:** Write a function that accepts an $n\times n$ matrix $A$ as an argument, and returns the three matrices $S$, $D$, and $S^{-1}$ such that $A=SDS^{-1}$.  Make use of the $\texttt{eig}$ function in SciPy.

**Solution:** We write a function that finds the diagonalization of an $n \times n$ matrix $A$ and then test it on the matrix $B$ defined in exercise 2 to check that it works.

In [20]:
def Diagonalization(A):
    '''
    Diagonalization(A)
    
    Diagonalization takes an nxn matrix A and computes the diagonalization
    of A. There is no error checking to ensure that the eigenvectors of A 
    form a linearly independent set.

    Parameters
    ----------
    A : NumPy array object of dimension nxn

    Returns
    -------
    S :        NumPy array object of dimension nxn
    D :        NumPy array object of dimension nxn
    S_inverse: Numpy array object of dimension nxn
    '''

    n = A.shape[0]  # n is number of rows and columns in A
    D = np.zeros((3,3),dtype='complex128')
    evalues,evectors = sla.eig(A)
    
    S = evectors
    S_inverse = lag.Inverse(S)
    
    for i in range(0,n,1):
        D[i][i] = evalues[i]
        
    return S,D,S_inverse

B = np.array([[2,0,0],[3,-2,1],[1,0,1]])
S, D, S_inverse = Diagonalization(B)
print(S,'\n')
print(D,'\n')
print(S_inverse)

[[0.         0.         0.57735027]
 [1.         0.31622777 0.57735027]
 [0.         0.9486833  0.57735027]] 

[[-2.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  1.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  2.+0.j]] 

[[-0.66666667  1.         -0.33333333]
 [-1.05409255  0.          1.05409255]
 [ 1.73205081  0.          0.        ]]


**Exercise 4:** Construct a $3\times 3$ matrix that is not diagonal and has eigenvalues 2, 4, and 10. 

**Solution:** If we want to construct a matrix $C$ with eigenvalues 2, 4, and 10, then $D$ must be a diagonal matrix with those eigenvalues as its diagonal entries. If we let $S$ be any $3 \times 3$ non diagonal matrix with linearly independent columns, then $C = SDS^{-1}$ will give us our desired matrix. We define $D$ and $S$ below, calculate $C$, and then check our answer using the $\texttt{eig}$ function.

$$
\begin{equation}
D = \left[ \begin{array}{rrr} 2 & 0 & 0  \\ 0 & 4 & 0 \\  0 & 0 & 10\end{array}\right] \hspace{2cm} S = \left[ \begin{array}{rrr} 1 & 1 & 0  \\ 0 & 1 & 1 \\  1 & 0 & 1\end{array}\right]
\end{equation}
$$

In [26]:
D = np.array([[2,0,0],[0,4,0],[0,0,10]])
S = np.array([[1,1,0],[0,1,1],[1,0,1]])
C = S@D@lag.Inverse(S)

print(C,'\n')

evalues,evectors = sla.eig(C)
print(evalues)

[[ 3.  1. -1.]
 [-3.  7.  3.]
 [-4.  4.  6.]] 

[10.+0.j  2.+0.j  4.+0.j]


The eigenvalues determined by $\texttt{eig}$ appear in a different order than we had originally, but are correct.

**Exercise 5:** Suppose that $C = QDQ^{-1}$ where

$$
\begin{equation}
Q = \left[ \begin{array}{c|c|c} & & \\ U & V & W \\ & & \end{array} \right] \hspace{2cm} D = \left[ \begin{array}{rrr} 0 & 0 & 0  \\ 0 & 3 & 0 \\  0 & 0 & 5 \end{array}\right]
\end{equation}
$$

$(a)$ Give a basis for $\mathcal{N}(C)$

$(b)$ Find all the solutions to $CX = V + W$

In [1]:
## Code solution here.