## Eigenvalues

In [1]:
import laguide as lag
import numpy as np
import scipy.linalg as sla
%matplotlib inline
import matplotlib.pyplot as plt
import math

**Exercise 1:** Determine the eigenvalues and corresponding eigenvectors of the following matrices by considering the transformations that they represent. Check your answers with a few computations.

$(a)$

$$
\begin{equation}
A = \left[ \begin{array}{cc} 1 & 0 \\ 0 & -3 \end{array}\right]
\end{equation}
$$

**Solution:**

Recall from [Chapter 4](Planar_Transformations.ipynb) that applying the transformation represented by $A$ is equivalent to stretching in the direction of the $y$-axis by a factor of 3 and then reflecting over the $y$-axis. If we imagine what this does to vectors in the plane then we might see that any vector that lies on the $x$-axis will be left unaffected. Therefore our first eigenvalue is $\lambda_1 = 1$ which corresponds to any scalar multiple of our first eigenvector $V_1 = \begin{equation} \left[ \begin{array}{cc} 1 \\ 0 \end{array}\right] \end{equation}$. Additionally, any vector that lies on the $y$-axis will simply be scaled by a factor of $-3$. Therefore our second eigenvalue is $\lambda_2 = -3$ which corresponds to any scalar multiple of our second eigenvector $V_2 = \begin{equation} \left[ \begin{array}{cc} 0 \\ 1 \end{array}\right] \end{equation}$.

In [5]:
A = np.array([[1,0],[0,-3]])
V1 = np.array([[1],[0]])
V2 = np.array([[0],[1]])
R = np.array([[5],[0]])
S = np.array([[1],[1]])
T = np.array([[0],[0]])

print(A@V1,'\n')
print(A@V2,'\n')
print(A@R,'\n')
print(A@S,'\n')
print(A@T)

[[1]
 [0]] 

[[ 0]
 [-3]] 

[[5]
 [0]] 

[[ 1]
 [-3]] 

[[0]
 [0]]


$(b)$

$$
\begin{equation}
B = \left[ \begin{array}{cc} 1 & 1 \\ 0 & 1 \end{array}\right]
\end{equation}
$$

**Solutions:**

Recall from [Chapter 4](Planar_Transformations.ipynb) that applying the transformation represented by $B$ is equivalent to shearing along the $x$-axis with a shearing factor of 1. Any vector that lies along the $x$-axis will be left unchanged because its $y$-coordinate is 0 and thus adds nothing to $x$-coordinate. Therefore our first eigenvalue is $\lambda_1 = 1$ which corresponds to any scalar multiple of our first eigenvector $V_1 = \begin{equation} \left[ \begin{array}{cc} 1 \\ 0 \end{array}\right] \end{equation}$. Any other vector with a nonzero $y$-coordinate will shear off of its original span, and thus cannot be a scalar multiple of itself. Therefore $V_1$ is the only eigenvalue of $B$.

In [6]:
B = np.array([[1,1],[0,1]])
V1 = np.array([[1],[0]])
V2 = np.array([[0],[1]])
R = np.array([[5],[0]])
S = np.array([[1],[1]])
T = np.array([[0],[0]])

print(B@V1,'\n')
print(B@V2,'\n')
print(B@R,'\n')
print(B@S,'\n')
print(B@T)

[[1]
 [0]] 

[[1]
 [1]] 

[[5]
 [0]] 

[[2]
 [1]] 

[[0]
 [0]]


$(c)$

$$
\begin{equation}
C = \left[ \begin{array}{cc} cos(\frac{\pi}{2}) & -sin(\frac{\pi}{2}) \\ sin(\frac{\pi}{2}) & cos(\frac{\pi}{2}) \end{array}\right]
\end{equation}
$$

**Solution:**

Recall from [Chapter 4](Planar_Transformations.ipynb) that applying the transformation represented by $C$ is equivalent to a rotation about the origin by the angle $\frac{\pi}{2}$. Any nonzero vector that is transformed by this matrix will be pointing directly perpendicular to its original direction, so cannot lie on its original span. Therefore $C$ has no eigenvalues nor any eigenvectors.

In [15]:
C = np.array([[math.cos(math.pi/2),-math.sin(math.pi/2)],[math.sin(math.pi/2),math.cos(math.pi/2)]])
V1 = np.array([[1],[0]])
V2 = np.array([[0],[1]])
R = np.array([[5],[0]])
S = np.array([[1],[1]])
T = np.array([[0],[0]])

print(np.round(C@V1),'\n')
print(np.round(C@V2),'\n')
print(np.round(C@R),'\n')
print(np.round(C@S),'\n')
print(np.round(C@T))

[[0.]
 [1.]] 

[[-1.]
 [ 0.]] 

[[0.]
 [5.]] 

[[-1.]
 [ 1.]] 

[[0.]
 [0.]]


$(d)$

$$
\begin{equation}
D = \left[ \begin{array}{cc} -0.6 & -0.8 \\ -0.8 & 0.6 \end{array}\right]
\end{equation}
$$