## Inner Products

In [7]:
import laguide as lag
import numpy as np
import scipy.linalg as sla
%matplotlib inline
import matplotlib.pyplot as plt
import math

**Exercise 1:** Create a Python function named $\texttt{Magnitude}$ that accepts as an argument vector in the form of a NumPy array object with shape $n\times 1$, and returns the magnitude of that vector.


In [2]:
def Magnitude(U):
    ''' 
    Magnitude(U)
    
    Magnitude computes the magnitude of U based on the Euclidean inner product
    
    Parameters
    ----------
    U : NumPy array object of dimension nx1
    
    Returns
    -------
    product: float
    '''
    # Check shape of U
    if (U.shape[1] != 1):
        print("Magnitude only accepts column vectors.")
        return
    
    magnitude = math.sqrt(DotProduct(U,U))
    return magnitude

**Exercise 2:** Use the $\texttt{random}$ module of NumPy to generate random $4\times 1$ vectors $U$, $V$, and $W$, and a random scalar $k$.  Verify the algebraic properties of the dot product listed above.  Try to make use of a conditional statement to check each statement.

We want to verify that the following equations hold for random $4 \times 1$ vectors $U, V,$ and $W$ and scalar $k$.
1. $U\cdot V = V\cdot U$
2. $U\cdot(V + W) = U\cdot V + U\cdot W$
3. $(kU)\cdot V = k(U\cdot V)$
4. $U\cdot U \ge 0$

In [6]:
U = np.random.randint(20,size=(4,1))
V = np.random.randint(20,size=(4,1))
W = np.random.randint(20,size=(4,1))
k = np.random.randint(20)

print(U,'\n')
print(V,'\n')
print(W,'\n')
print(k,'\n')

if (lag.DotProduct(U,V) == lag.DotProduct(V,U)):
    print("The dot product is commutative. \n")
if (lag.DotProduct(U,V+W) == lag.DotProduct(U,V) + lag.DotProduct(U,W)):
    print("The dot product distributes over vector addition. \n")
if (lag.DotProduct(k*U,V) == k*lag.DotProduct(U,V)):
    print("The dot product is associative with respect to scalar multiplication. \n")
if (lag.DotProduct(U,U) >= 0):
    print("The dot product of a vector with itself is greater than or equal to 0 \n")

[[ 7]
 [19]
 [11]
 [11]] 

[[8]
 [0]
 [6]
 [1]] 

[[12]
 [14]
 [12]
 [18]] 

9 

The dot product is commutative. 

The dot product distributes over vector addition. 

The dot product is associative with respect to scalar multiplication. 

The dot product of a vector with itself is greater than or equal to 0 



**Exercise 3:** Let $X$ and $Y$ be the following vectors.

$$
\begin{equation}
X = \left[ \begin{array}{r} 3 \\ -1 \\ 2  \end{array}\right] \hspace{1cm} 
Y = \left[ \begin{array}{r} 4 \\ 2 \\ 0  \end{array}\right] 
\end{equation}
$$

$(a)$ Determine the angle between $X$ and $Y$.  (*You will need the $\texttt{acos}$ function in Python's $\texttt{math}$ module.*)

We will use the following equation to determine the angle $\theta$ between $X$ and $Y$, as well as the $\texttt{DotProduct}$ and $\texttt{Magnitude}$ functions.

$$
\begin{equation}
\cos{\theta} = \frac{X\cdot Y}{||X||||Y||}
\end{equation}
$$

In [8]:
X = np.array([[3],[-1],[2]])
Y = np.array([[4],[2],[0]])
print(math.acos((lag.DotProduct(X,Y))/((lag.Magnitude(X))*(lag.Magnitude(Y)))))

0.9302740141154721


$(b)$ Find a vector in $\mathbb{R}^3$ that is orthogonal to the vector $X$.  Verify your answer with a computation.

Two vectors are **orthogonal** if their dot product is zero. The vector $W$ defined below is an example of a vector that is orthogonal to $X$.

$$
\begin{equation}
W = \left[ \begin{array}{r} 1 \\ 3 \\ 0  \end{array}\right] 
\end{equation}
$$

In [38]:
X = np.array([[3],[-1],[2]])
W = np.array([[1],[3],[0]])
print(lag.DotProduct(X,W))

0.0


$(c)$ Construct a unit vector $Z$ such that $Z\cdot Y = -||Y||$.  Verify your answer with a computation.

First we calculate $-||Y|| = -\sqrt{4^2 + 2^2 + 0^2} = -2\sqrt{5}$. If we define the arbitrary vector $Z$ as below, then we see that we need to find values for $z_1, z_2$, and $z_3$ such that $||Z|| = \sqrt{(z_1)^2 + (z_2)^2 + (z_3)^2} = 1$ and $Z \cdot Y = 4z_1 + 2z_2 + 0z_3 = -2\sqrt{5}$.

$$
\begin{equation}
Z = \left[ \begin{array}{r} z_1 \\ z_2 \\ z_3  \end{array}\right] 
\end{equation}
$$

Since $z_3$ contributes nothing to the second sum above, lets set $z_3 = 0$ for simplicities sake. This gives a system of two equations in two unknowns, namely

$$
\begin{eqnarray*}
4z_1 + 2z_2 & = & -2\sqrt{5} \\
z_1^2 + z_2^2 & = & 1 \\
\end{eqnarray*}
$$

Note that we can't solve this system using elimination because the second equation is not linear.  Instead, if we solve for one of the variables in the first equation and substitute into the second, we will be able to use the quadratic formula to find a solution. Solving for $z_2$ in the first equation, we get

$$
\begin{eqnarray*}
z_2 & = & -\sqrt{5} - 2z_1 \\
\end{eqnarray*}
$$

Next we substitute this equality in for $z_2$ in our second equation, multiply out and move everything to the left.

$$
\begin{eqnarray*}
5z_1^2 + 4\sqrt{5}z_1 + 4 = 0 \\
\end{eqnarray*}
$$

Using the quadratic formula reveals that the two roots of this equation are equal, namely $z_1 = -\frac{2}{5}\sqrt{5}$. If we substitute this into the equation above where we had solved for $z_2$, we see that $z_2 = -\frac{1}{5}\sqrt{5}$ and thus the vector $Z$ below is a solution to our problem.

$$
\begin{equation}
Z = \left[ \begin{array}{r} -\frac{2\sqrt{5}}{5} \\ -\frac{\sqrt{5}}{5} \\ 0  \end{array}\right] 
\end{equation}
$$

In [47]:
Y = np.array([[4],[2],[0]])
Z = np.array([[-2*np.sqrt(5)/5],[-np.sqrt(5)/5],[0]])
print(lag.DotProduct(Z,Y),'\n')
print(-lag.Magnitude(Y),'\n')
print(lag.Magnitude(Z))

-4.47213595499958 

-4.47213595499958 

1.0


**Exercise 4:** Create a Python function named $\texttt{DifferenceMagnitude}$ which takes two $n \times 1$ vectors as arguments and returns the magnitude of their difference. Use this function to determine $|| X - Y||$ where vectors $X$ and $Y$ are given below.

$$
\begin{equation}
X = \left[ \begin{array}{r} 3 \\ -1 \\ 2  \end{array}\right] \hspace{1cm} 
Y = \left[ \begin{array}{r} 4 \\ 2 \\ 0  \end{array}\right] 
\end{equation}
$$

In [2]:
# Building the function Difference Magnitude where X and y are two column vectors.

def DifferenceMagnitude(X,Y):
    Z = X - Y
    diffMag = sqrt(lag.DotProduct(Z,Z))
    return diffMag

X = np.array([[3],[-1],[2]])
Y = np.array([[4],[2],[0]])

print(DifferenceMagnitude(X,Y))

3.7416573867739413


We can see from the computations that $||X - Y|| = 3.714$.

**Exercise 5:** Create a Python function which takes an $n \times 1$ vector as its argument and returns the unit vector of the argument vector. Use the NumPy $\texttt{random}$ module to generate a random $3 \times 1 $ vector, and test this function on that vector.

In [14]:
## Creating the UnitVector function

def UnitVector(X):
    mag = sqrt(lag.DotProduct(X,X))
    unitVect = X/mag
    
    return unitVect

## Building a random vector
X = np.random.randint(10,size = (3,1))
print("X: \n" , X, '\n')
print("The unit vector of X: \n", UnitVector(X), '\n')

X: 
 [[9]
 [8]
 [8]] 

The unit vector of X: 
 [[0.62254302]
 [0.55337157]
 [0.55337157]] 



**Exercise 6:** Find a vector $Y$ in $\mathbb{R}^2$ such that $X\cdot Y = ||Y - X||$ where the vector $X$ is given below. Is the vector $Y$ unique ? Verify your answer through a computation.

$$
\begin{equation}
X = \left[ \begin{array}{r} 1 \\ 1  \end{array}\right] 
\end{equation}
$$

#### Solution:

Let us assume that the vector $Y$ in $\mathbb{R}^2$ is as follows:


$$
\begin{equation}
Y = \left[ \begin{array}{r} a \\ b  \end{array}\right] 
\end{equation}
$$


where $a$, $b$ are some scalars.


So, $$
\begin{equation}
Y  - X= \left[ \begin{array}{r} a - 1 \\ b - 1  \end{array}\right] 
\end{equation}
$$


$||Y - X||^2 = (a-1)^2 + (b-1)^2 $

$X\cdot Y = a + b$

As $X\cdot Y = ||Y - X||$ , $(X\cdot Y)^2 = ||Y - X||^2 $.

So, $ (a+b)^2 = (a - 1)^2 + (b-1)^2 $

$ a^2 + b^2 + 2ab = a^2 + 1 - 2a + b^2 + 1 - 2b$

$ 2ab = 2 - 2a - 2b$

 $2a + 2b + 2ab = 2$

$ a + b + ab = 1$

The above equation is true for two possible set of real values of $a$ and $b$. First case is when $a = 0$ and $b = 1$, and second case is when $a = 1$ and $b = 0$.

Therefore, we get two possible vectors $Y$ which are as follows:

So, $$
\begin{equation}
Y = \left[ \begin{array}{r} 1 \\ 0  \end{array}\right] \hspace{1cm} or \hspace{1cm}
Y = \left[ \begin{array}{r} 0 \\ 1  \end{array}\right]
\end{equation}
$$


This implies that the vector $Y$ is not unique. We can verify our results in the code cell below.

In [17]:
# Building vectors X and Y:

X = np.array([[1],[1]])
Y_1 = np.array([[1],[0]])
Y_2 = np.array([[0],[1]])

dotProd1 = lag.DotProduct(X, Y_1)
dotProd2 = lag.DotProduct(X, Y_2)

diffMag1 = DifferenceMagnitude(Y_1, X )
diffMag2 = DifferenceMagnitude(Y_2, X)

print("Dot product of X and Y_1 is: \n", dotProd1, '\n')
print("The magnitude of difference of Y_1 and X is: \n", diffMag1, '\n')

print("Dot product of X and Y_2 is: \n", dotProd2, '\n')
print("The magnitude of difference of Y_2 and X is: \n", diffMag2, '\n')

Dot product of X and Y_1 is: 
 1.0 

The magnitude of difference of Y_1 and X is: 
 1.0 

Dot product of X and Y_2 is: 
 1.0 

The magnitude of difference of Y_2 and X is: 
 1.0 



The computations done in the above code cell demonstrate that the vector $Y$ is not unique.

**Exercise 7:** Create a Python function named $\texttt{Angle}$ which takes two vectors as arguments and returns $\cos{\theta}$ where ${\theta}$ is the angle between the two vectors. Use this function to show that vectors $U$ and $W$ are orthogonal.

$$
\begin{equation}
U = \left[ \begin{array}{r} 1 \\ -1 \\ 2  \end{array}\right] \hspace{1cm} 
W = \left[ \begin{array}{r} 2 \\ 0 \\ -1  \end{array}\right] 
\end{equation}
$$

In [18]:
## Building the function Angle

def Angle(X,Y):
    dotProd = lag.DotProduct(X, Y)
    magX = sqrt(lag.DotProduct(X, X))
    magY = sqrt(lag.DotProduct(Y, Y))
    cos_theta = dotProd/(magX*magY)
    
    return cos_theta

U = np.array([[1],[-1],[2]])
W = np.array([[2],[0],[-1]])

print(Angle(U, W))

0.0


We can see that $\cos{\theta} = 0$ for vectors $U$ and $W$ which means that $\theta = 90^{\circ}$. This implies that $U$ and $W$ are orthogonal vectors.

**Exercise 8:** Given that $||X+Y|| = 3$, $X\cdot Y = 2$, find $||X-Y||$.

#### Solution:

We know that $||X + Y||^2 = (X+Y)\cdot (X+Y)$

$||X + Y||^2 = ||X||^2 + ||Y||^2 + 2X\cdot Y$

Given $||X + Y||$ and $X\cdot Y$,we can find $||X||^2  + ||Y||^2$ as follows:

$ (3)^2 = ||X||^2 + ||Y||^2 + 2(2)$

$||X||^2 + ||Y||^2 = 5$

Now, $||X - Y||^2 = (X-Y)\cdot (X-Y)$

$||X - Y||^2 = ||X||^2 + ||Y||^2 - 2X\cdot Y$

We can now substitute the values for $||X||^2 + ||Y||^2$ and $X\cdot Y$ to get:

$||X - Y||^2 = 5 - 2(2)$

$||X - Y||^2 = 1$

Therefore, $||X - Y|| = 1$

### Orthogonalization

**Exercise 4:** Find a vector that is orthogonal to the column space of the matrix $A$.

$$
\begin{equation}
A = \left[ \begin{array}{rr} 1 & 2\\ 2 & 0 \\ 3 & 1\end{array}\right] 
\end{equation}
$$

#### Solution:

Since there is a pivot in each column of the matrix $A$, the basis for the column space of $A$ consists of the two column vectors. 

Let 


$$
\begin{equation}
X_1 = \left[ \begin{array}{r} 1 \\ 2 \\ 3 \end{array}\right] \hspace{1cm}
X_2 = \left[ \begin{array}{r} 2 \\ 0 \\ 1 \end{array}\right] 
\end{equation}
$$

Then the basis for the column space of $A$ is $\{X_1,X_2\}$. Let us consider a vector $Y$ which is orthogonal to vectors $X_1$, $X_2$. This means that $X_1\cdot Y = 0$ and $X_2\cdot Y=0$.

Let

$$
\begin{equation}
Y = \left[ \begin{array}{r} a \\ b \\ c \end{array}\right] \hspace{1cm} 
\end{equation}
$$

where $a$, $b$, $c$ are some scalars.

The conditions $X_1\cdot Y = 0$ and $X_2\cdot Y=0$ gives a system of equations to solve:


$$
\begin{eqnarray*}
a + 2b + 3c & = & 0\\
2a\,\,\,\,\,\,\,\,\,\,\,\,\, + c & = & 0\\ 
\end{eqnarray*}
$$

Since $c$ is a free variable we let $c = t$, where $t$ is some real number.  From the above two equations, we can then find the values of $a$ and $b$ in terms of $t$.

$a = -t/2$  and $b = -5t/4$.


Therefore, the vector $Y$ is as follows:


$$
\begin{equation}
Y = t\left[ \begin{array}{r} -1/2 \\ -5/4 \\ 1 \end{array}\right] \hspace{1cm} 
\end{equation}
$$



So, one particular vector orthogonal to the column space of $A$ is:


$$
\begin{equation}
\left[ \begin{array}{r} -1/2 \\ -5/4 \\ 1 \end{array}\right] \hspace{1cm} 
\end{equation}
$$

**Exercise 5:** Let $U = \texttt{Span}\{v_1,v_2\}$ where $v_1$, $v_2$ are given below. Perform the Gram-Schimdt orthogonalization to produce an orthonormal basis $\{u_1,u_2\}$ for $U$ and verify your answer.


$$
\begin{equation}
v_1 = \left[ \begin{array}{r} 1 \\ 1 \\ 2 \end{array}\right] \hspace{1cm}
v_2 = \left[ \begin{array}{r} 2 \\ 1 \\ 3 \end{array}\right] 
\end{equation}
$$

#### Solution:


Let $\{w_1,w_2\}$ be an orthogonal basis for $U$. We would first go about producing an orthogonal basis for $U$. We can then scale the orthogonal vectors to produce an orthonormal basis for $U$.

In [16]:
## Generating the orthogonal vectors w_1 and w_2:

v_1 = np.array([[1],[1],[2]])
v_2 = np.array([[2],[1],[3]])

w_1 = v_1 
w_2 = v_2 - (lag.DotProduct(w_1, v_2)/lag.DotProduct(w_1, w_1))*w_1

print("w_1: \n", w_1, '\n')
print("w_2:  \n", w_2, '\n')

# Generating the orthonormal vectors by scaling the orthogonal vectors:

u_1 = w_1/sqrt(lag.DotProduct(w_1,w_1))
u_2 = w_2/sqrt(lag.DotProduct(w_2,w_2))

print("u_1: \n", u_1, '\n')
print("u_2: \n", u_2, '\n')

# Verifying that u_1 and u_2 are orthonormal.

print("The dot product of u_1 and u_2 is: \n", lag.DotProduct(u_1,u_2),'\n')
print("The magnitude of u_1 is: \n", sqrt(lag.DotProduct(u_1,u_1)), '\n')
print("The magnitude of u_2 is: \n", np.round(sqrt(lag.DotProduct(u_2,u_2)), 2), '\n')

w_1: 
 [[1]
 [1]
 [2]] 

w_2:  
 [[ 0.5]
 [-0.5]
 [ 0. ]] 

u_1: 
 [[0.40824829]
 [0.40824829]
 [0.81649658]] 

u_2: 
 [[ 0.70710678]
 [-0.70710678]
 [ 0.        ]] 

The dot product of u_1 and u_2 is: 
 0.0 

The magnitude of u_1 is: 
 1.0 

The magnitude of u_2 is: 
 1.0 



**Exercise 6:** Let $v$ be a vector in $\mathbb{R}^4$. Explain why the set of vectors orthogonal to $v$ is a subspace of $\mathbb{R}^4$.

#### Solution:  

Let $U$ be the set of all vectors which are orthogonal to the vector $v$. Let us consider two vectors $x$ and $y$ in $U$.

The vectors $v$, $x$ and $y$ are as follows:


$$
\begin{equation}
v = \left[ \begin{array}{r} v_1 \\ v_2 \\ v_3 \\ v_4 \end{array}\right] \hspace{1cm}
x = \left[ \begin{array}{r}  x_1 \\ x_2 \\ x_3 \\ x_4 \end{array}\right] \hspace{1cm}
y = \left[ \begin{array}{r}  y_1 \\ y_2 \\ y_3 \\ y_4 \end{array}\right] \hspace{1cm}
\end{equation}
$$


where all the enteries are some scalars.


Since vectors $x$ and $y$ are in $U$, the vectors $x$ and $y$ need to be orthogonal to the vector $v$. This basically means that $x\cdot v = 0$ and $y\cdot v = 0$.


So, $x_1v_1 + x_2v_2 +x_3v_3 + x_4v_4 = 0$ ,

$y_1v_1 + y_2v_2 +y_3v_3 + y_4v_4 = 0$.

On adding the two equations, we get

$(x_1 + y_1)v_1 + (x_2 + y_2)v_2 + (x_3 + y_3)v_3 + (x_4 + y_4)v_4 = 0$

The *LHS* is actually the dot product of vector $(x+y)$ with $v$ and since the dot product of vector $(x + y)$ with $v$ equals 0, $(x+y)$ is also in $U$.


On multiplying the equation $x_1v_1 + x_2v_2 +x_3v_3 + x_4v_4 = 0$ by $k$ on both sides, we get:


$kx_1v_1 + kx_2v_2 + kx_3v_3 + kx_4v_4 = k(0) = 0$

The *LHS* of the above equation is basically the dot product of $kx$ and $v$ which also equals zero. Therefore, $kx$ is orthogonal to $v$ and hence, $kx$ is also present in $U$.


This imples that for any two vectors $x$ and $y$ in $U$, vectors $(x+y)$ and $kx$ are also present in $U$. This satisfies the condition for a subspace and therefore, $U$ is a subspace of $\mathbb{R}^4$.

**Exercise 7:** Given vectors $V$ and $W$, find vectors $X$ and $Y$ such that $X$ is the projection of $V$ in the direction of $W$ and $V = X + Y$. Verify your answer.


$$
\begin{equation}
V = \left[ \begin{array}{r} 
9\\ 5 \\ 0 \end{array}\right] \hspace{1cm}
W = \left[ \begin{array}{r} 3 \\ 0 \\ 3 \end{array}\right] 
\end{equation}
$$

In [24]:
## Building vectors V and W:

V = np.array([[9],[5],[0]])
W = np.array([[3],[0],[5]])

X = (lag.DotProduct(V, W)/lag.DotProduct(W, W))*W
Y = V - X

print("X: \n", X, '\n')
print("Y: \n", Y, '\n')

# Verifying if X and Y are orthogonal to each other.

print("The dot product of X and Y is: \n", np.round(lag.DotProduct(X, Y), 8), '\n' )

X: 
 [[2.38235294]
 [0.        ]
 [3.97058824]] 

Y: 
 [[ 6.61764706]
 [ 5.        ]
 [-3.97058824]] 

The dot product of X and Y is: 
 0.0 



**Exercise 8:** Let $U$ be a vector space spanned by the columns of $A$. Find an orthonormal basis for $U$ to generate an orthogonal matrix $Q$. Verify that $Q^TQ = I$ where $I$ is the identity matrix.


$$
\begin{equation}
A = \left[ \begin{array}{r} 1 & 2 & -1\\ 0 & 2 & 1 \\  1 & 1 & 2 \end{array}\right]  
\end{equation}
$$

In [18]:
## Building the matrix A

A = np.array([[1,2,-1],[0,2,1],[1,1,2]])
A_red = lag.FullRowReduction(A)

print("A_reduced: \n", A_red, '\n')

A_reduced: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



We can see from the above code cell that there is a pivot in each column of $A$. Therefore, the column vectors of $A$ are linearly independent. As $U$ is spanned by the columns of $A$ and the columns of $A$ are linearly independent, we can say that the columns of $A$ are a basis for the vector space $U$.

Let 


$$
\begin{equation}
x_1 = \left[ \begin{array}{r} 1\\ 0 \\ 1 \end{array}\right] \hspace{1cm}
x_2 = \left[ \begin{array}{r} 2 \\ 2 \\ 1 \end{array}\right] \hspace{1cm}
x_3 = \left[ \begin{array}{r} -1 \\ 1 \\ 2 \end{array}\right] \hspace{1cm}
\end{equation}
$$


Then, $U = \texttt{Span}\{x_1,x_2,x_3\}$. Now, we can perform **Gram-Schimdt** orthogonalization on the bases vectors $x_1$, $x_2$, and $x_3$ to get the orthonormal vectors. 

In [19]:
## building the vectors X_1, X_2, X_3:

X_1 = np.array([[1],[0],[1]])
X_2 = np.array([[2],[2],[1]])
X_3 = np.array([[-1],[1],[2]])

## Let the orthogonal vectors be W_1, W_2, W_3:

W_1 = X_1
W_2 = X_2 - (lag.DotProduct(X_2, W_1)/lag.DotProduct(W_1, W_1))*W_1
W_3 = X_3 - (lag.DotProduct(X_3, W_1)/lag.DotProduct(W_1, W_1))*W_1 - (lag.DotProduct(X_3, W_2)/lag.DotProduct(W_2, W_2))*W_2

## Let the orthonormal vectors be U_1, U_2, U_3

U_1 = W_1/sqrt(lag.DotProduct(W_1, W_1))
U_2 = W_2/sqrt(lag.DotProduct(W_2, W_2))
U_3 = W_3/sqrt(lag.DotProduct(W_3, W_3))


print("U_1: \n", U_1, '\n')
print("U_2: \n", U_2, '\n')
print("U_3: \n", U_3, '\n')

## Stacking the orthonormal vectors in a matrix to get the orthogonal matrix Q:

Q = np.hstack([U_1,U_2, U_3])
print("Q: \n", Q, '\n')


## Verification:
Q_T = np.transpose(Q)
I = np.eye(3)


print("Q_T@Q: \n", np.round(Q_T@Q, 8), '\n')
print("I: \n", I, '\n')

U_1: 
 [[0.70710678]
 [0.        ]
 [0.70710678]] 

U_2: 
 [[ 0.23570226]
 [ 0.94280904]
 [-0.23570226]] 

U_3: 
 [[-0.66666667]
 [ 0.33333333]
 [ 0.66666667]] 

Q: 
 [[ 0.70710678  0.23570226 -0.66666667]
 [ 0.          0.94280904  0.33333333]
 [ 0.70710678 -0.23570226  0.66666667]] 

Q_T@Q: 
 [[ 1. -0. -0.]
 [-0.  1. -0.]
 [-0. -0.  1.]] 

I: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



In the above code cell, we used **Gram-Schimdt** Orthogonalization to generate a set of orthonormal bases i.e $\{U_1,U_2,U_3\}$. Then, we can generate a matrix $Q$ which contains the orthonormal vectors as its columns. We have also verified that $Q^TQ = I$.

**Exercise 9:** Consider two vectors $X$ and $Y$. Given that $Z$ is the projection of $X$ in the direction of $Y$ and $X \cdot Y = 6$, find $Y$.


$$
\begin{equation}
X = \left[ \begin{array}{r} 2\\ 1 \\ 1 \end{array}\right] \hspace{1cm}
Z = \left[ \begin{array}{r} 1 \\ 1 \\ 0 \end{array}\right] 
\end{equation}
$$

#### Solution:

We have been given that the vector $Z$ is in the direction of vector $Y$. Therefore, the angle between the vector $X$ and the vector $Z$ is same as the angle between the vectors $X$ and $Y$. 

The angle between the vectors $X$ and $Z$ is as follows:

$$
\begin{equation}
\cos{\theta} = \frac{X\cdot Z}{||X||||Z||} = \frac{3}{\sqrt{2} \sqrt{6}} = \frac{\sqrt{3}}{2}
\end{equation}
$$

Hence, $\theta = 30^{\circ}$ and this is also the angle between vectors $X$ and $Y$.


$$
\begin{equation}
\cos{30^{\circ}} = \frac{X\cdot Y}{||X||||Y||} = \frac{6}{\sqrt{6}||Y||} = \frac{\sqrt{3}}{2}
\end{equation}
$$

From here, we can get $||Y||$ as follows:


$$
\begin{equation}
||Y|| = \frac{2\sqrt{6}}{\sqrt{3}} = 2\sqrt{2}
\end{equation}
$$


Now, let us find  unit vector in the direction of $Y$. Unit vector in the direction of $Z$ is also the unit vector in the direction of $Y$.

$\hat{Y} =  \frac{Z}{||Z||}$


$$
\begin{equation}
\hat{Y} = \left[ \begin{array}{r} \frac{1}{\sqrt{2}}\\ \frac{1}{\sqrt{2}} \\ 0 \end{array}\right] 
\end{equation}
$$



Therefore, the vector $Y$ is as follows:


$$
\begin{equation}
Y = \hat{Y}||Y|| = 2\sqrt{2}\left[ \begin{array}{r} \frac{1}{\sqrt{2}}\\ \frac{1}{\sqrt{2}} \\ 0 \end{array}\right] =  
\left[ \begin{array}{r} 2 \\ 2 \\ 0 \end{array}\right] 
\end{equation}
$$
