## Linear Transformations

In [1]:
import laguide as lag
import numpy as np
import scipy.linalg as sla
%matplotlib inline
import matplotlib.pyplot as plt

**Exercise 1:** Find the vector $T(V)$ where

$$
\begin{equation}
V = \left[\begin{array}{r} 1 \\ 3 \end{array} \right]
\end{equation}
$$

We use the definition of $T$ to find $T(V)$ and then check our answer by using the $\texttt{T}$ function that we defined.

$$
\begin{equation}
T(V) = T \left(\left[ \begin{array}{rr} 1 \\ 3 \end{array}\right]\right)
= \left[ \begin{array}{rr} 2(1) \\ 0 \\ (3) \end{array}\right]
= \left[ \begin{array}{rr} 2 \\ 0 \\ 3 \end{array}\right]
\end{equation}
$$

In [2]:
def T(V):
    W = np.zeros((3,1))
    W[0,0] = 2*V[0,0]
    W[2,0] = V[1,0]
    return W

V = np.array([[1],[3]])
print(T(V))

[[2.]
 [0.]
 [3.]]


**Exercise 2:** Find the vector $U$ so that 

$$
\begin{equation}
T(U) = \left[\begin{array}{r} 5 \\ 0 \\ -1 \end{array} \right]
\end{equation}
$$

If we start by taking $U$ to be an arbitrary vector in $\mathbb{R}^2$ with entries $u_1$ and $u_2$, then we get the following vector equation for $U$.

$$
\begin{equation}
T(U) = T \left(\left[\begin{array}{r} u_1 \\ u_2 \end{array} \right]\right)
= \left[\begin{array}{r} 2u_1 \\ 0 \\ u_2 \end{array} \right]
= \left[\begin{array}{r} 5 \\ 0 \\ -1 \end{array} \right]
\end{equation}
$$

We can see that $2u_1 = 5$ so $u_1 = 2.5$ and $u_2 = -1$. Therefore $U = \left[\begin{array}{r} 2.5 \\ -1 \end{array} \right]$

**Exercise 3:** Write a Python function that implements the transformation $N:\mathbb{R}^3\to\mathbb{R}^2$, given by the following rule.  Use the function to find evidence that $N$ is **not linear**.

$$
\begin{equation}
N \left(\left[\begin{array}{r} v_1 \\ v_2 \\ v_3 \end{array} \right]\right) = 
\left[\begin{array}{c} 8v_2 \\  v_1 + v_2 + 3 \end{array} \right]
\end{equation}
$$

In [3]:
def N(V):
    W = np.zeros((2,1))
    W[0,0] = 8*V[1,0]
    W[1,0] = V[0,0] + V[1,0] + 3
    return W

One of the requirements for $N$ to be linear is that $N(V+W) = N(V) + N(W)$ for all vectors $V,W$ in $\mathbb{R}^3$. Any choice of $V$ and $W$ shows that this is not the case, however, and so $N$ is not linear.

In [4]:
V = np.array([[1],[1],[1]])
W = np.array([[1],[2],[3]])
print(N(V + W),'\n')
print(N(V) + N(W))

[[24.]
 [ 8.]] 

[[24.]
 [11.]]


**Exercise 4:** Consider the two transformations, $S$ and $R$, defined below.  Write a Python function that implements the composition $R\circ S$.  Explain why it is not possible to form the composition $S \circ R$.

$$
\begin{equation}
S \left(\left[\begin{array}{r} v_1 \\ v_2 \\ v_3 \end{array} \right]\right) = 
\left[\begin{array}{c}   v_1 + v_2 \\  3v_3 \end{array} \right]
\end{equation}
$$

$$
\begin{equation}
R \left(\left[\begin{array}{r} v_1 \\ v_2  \end{array} \right]\right) = 
\left[\begin{array}{rr} 3 &  0 \\ -1 & 1 \end{array}\right]
\left[\begin{array}{c}   v_1 \\ v_2 \end{array} \right]
\end{equation}
$$
  

We will first write a function for each of $S$ and $R$, and then we will write a function that implements the composition $R \circ S$ by first applying $S$ and then applying $R$ to the output of that transformation. We will confirm that it is working correctly by testing with an example vector.

In [5]:
def S(V):
    W = np.zeros((2,1))
    W[0,0] = V[0,0] + V[1,0]
    W[1,0] = 3*V[2,0]
    return W

def R(V):
    T = np.array([[3,0],[-1,1]])
    W = T@V
    return W

def R_composed_with_S(V):
    W = R(S(V))
    return W

V = np.array([[1],[4],[-2]])
print(R_composed_with_S(V))

[[ 15.]
 [-11.]]


$$
\begin{equation}
R \left(S\left(\left[\begin{array}{r} 1 \\ 4 \\ -2 \end{array} \right]\right)\right) 
= R \left(\left[\begin{array}{r} 5 \\ -6 \end{array} \right]\right)
= \left[\begin{array}{r} 3 & 0 \\ -1 & 1 \end{array} \right] \left[\begin{array}{r} 5 \\ -6 \end{array} \right]
= \left[\begin{array}{r} 15 \\ -11 \end{array} \right]
\end{equation}
$$

It is impossible to form the composition $S \circ R$ because this requires applying the transformation $S$ to the output of the mapping $R$, but $R$ outputs vectors in $\mathbb{R}^2$ and $S$ needs input vectors from $\mathbb{R}^3$.

### Matrix Representations

**Exercise 1:** For each of the following linear transformations, find the standard matrix representation, and then determine if the transformation is onto, one-to-one, or invertible.

$(a)$

$$
\begin{equation}
B \left(\left[\begin{array}{r} x_1 \\ x_2 \\ x_3 \\ x_4 \end{array} \right]\right) = 
\left[\begin{array}{c} x_1 + 2x_2 - x_3 -x_4 \\ x_2 -3x_3 +2x_4 \end{array} \right]
\end{equation}
$$

$B$ maps $\mathbb{R}^4$ to $\mathbb{R}^2$ so to find the standard matrix representation of $B$, we have to first apply the formula to each of the four standard basis vectors of $\mathbb{R}^4$.

$$
\begin{equation}
B\left(\left[\begin{array}{r} 1\\0\\0\\0 \end{array}\right]\right)= \left[\begin{array}{r} 1\\0 \end{array}\right] \hspace{1cm} 
B\left(\left[\begin{array}{r} 0\\1\\0\\0 \end{array}\right]\right)= \left[\begin{array}{r} 2\\1 \end{array}\right] \hspace{1cm} 
B\left(\left[\begin{array}{r} 0\\0\\1\\0 \end{array}\right]\right)= \left[\begin{array}{r} -1\\-3 \end{array}\right] \hspace{1cm}
B\left(\left[\begin{array}{r} 0\\0\\0\\1 \end{array}\right]\right)= \left[\begin{array}{r} -1\\2 \end{array}\right] 
\end{equation}
$$

We build $[B]$ by using these images as the columns and then find the RREF using $\texttt{FullRowReduction}$.

$$
\begin{equation}
[B] = \left[\begin{array}{rr} 1 & 2 & -1 & -1 \\ 0 & 1 & -3 & 2 \end{array}\right]
\end{equation}
$$

In [3]:
B = np.array([[1,2,-1,-1],[0,1,-3,2]])
print(lag.FullRowReduction(B))

[[ 1.  0.  5. -5.]
 [ 0.  1. -3.  2.]]


The RREF of $[B]$ has a pivot in every row, but not in the third and fourth columns. Therefore $B$ is onto but not one-to-one.

$(b)$

$$
\begin{equation}
C \left(\left[\begin{array}{r} x_1 \\ x_2 \\ x_3 \end{array} \right]\right) = 
\left[\begin{array}{c} x_1 -x_2 + 8x_3 \\ 4x_1 + 5x_2 - x_3 \\ -x_1 -x_2 + 3x_3 \end{array} \right]
\end{equation}
$$

$C$ maps $\mathbb{R}^3$ to $\mathbb{R}^3$ so to find the standard matrix representation of $C$, we have to first apply the formula to each of the three standard basis vectors of $\mathbb{R}^3$.

$$
\begin{equation}
C\left(\left[\begin{array}{r} 1\\0\\0 \end{array}\right]\right)= \left[\begin{array}{r} 1\\4\\-1 \end{array}\right]\hspace{1cm} 
C\left(\left[\begin{array}{r} 0\\1\\0 \end{array}\right]\right)= \left[\begin{array}{r} -1\\5\\-1 \end{array}\right]\hspace{1cm} 
C\left(\left[\begin{array}{r} 0\\0\\1 \end{array}\right]\right)= \left[\begin{array}{r} 8\\-1\\3 \end{array}\right]
\end{equation}
$$

We build $[C]$ by using these images as the columns and then find the RREF using $\texttt{FullRowReduction}$.

$$
\begin{equation}
[C] = \left[\begin{array}{rr} 1 & -1 & 8 \\ 4 & 5 & -1 \\ -1 & -1 & 3\end{array}\right]
\end{equation}
$$

In [4]:
C = np.array([[1,-1,8],[4,5,-1],[-1,-1,3]])
print(lag.FullRowReduction(C))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


The RREF of $[C]$ has a pivot in every row and column. Therefore $C$ is onto and one-to-one, which means it is invertible.