## Linear Transformations

In [1]:
import laguide as lag
import numpy as np
import scipy.linalg as sla
%matplotlib inline
import matplotlib.pyplot as plt

**Exercise 1:** Find the vector $T(V)$ where

$$
\begin{equation}
V = \left[\begin{array}{r} 1 \\ 3 \end{array} \right]
\end{equation}
$$

We use the definition of $T$ to find $T(V)$ and then check our answer by using the $\texttt{T}$ function that we defined.

$$
\begin{equation}
T(V) = T \left(\left[ \begin{array}{rr} 1 \\ 3 \end{array}\right]\right)
= \left[ \begin{array}{rr} 2(1) \\ 0 \\ (3) \end{array}\right]
= \left[ \begin{array}{rr} 2 \\ 0 \\ 3 \end{array}\right]
\end{equation}
$$

In [2]:
def T(V):
    W = np.zeros((3,1))
    W[0,0] = 2*V[0,0]
    W[2,0] = V[1,0]
    return W

V = np.array([[1],[3]])
print(T(V))

[[2.]
 [0.]
 [3.]]


**Exercise 2:** Find the vector $U$ so that 

$$
\begin{equation}
T(U) = \left[\begin{array}{r} 5 \\ 0 \\ -1 \end{array} \right]
\end{equation}
$$

If we start by taking $U$ to be an arbitrary vector in $\mathbb{R}^2$ with entries $u_1$ and $u_2$, then we get the following vector equation for $U$.

$$
\begin{equation}
T(U) = T \left(\left[\begin{array}{r} u_1 \\ u_2 \end{array} \right]\right)
= \left[\begin{array}{r} 2u_1 \\ 0 \\ u_2 \end{array} \right]
= \left[\begin{array}{r} 5 \\ 0 \\ -1 \end{array} \right]
\end{equation}
$$

We can see that $2u_1 = 5$ so $u_1 = 2.5$ and $u_2 = -1$. Therefore $U = \left[\begin{array}{r} 2.5 \\ -1 \end{array} \right]$

**Exercise 3:** Write a Python function that implements the transformation $N:\mathbb{R}^3\to\mathbb{R}^2$, given by the following rule.  Use the function to find evidence that $N$ is **not linear**.

$$
\begin{equation}
N \left(\left[\begin{array}{r} v_1 \\ v_2 \\ v_3 \end{array} \right]\right) = 
\left[\begin{array}{c} 8v_2 \\  v_1 + v_2 + 3 \end{array} \right]
\end{equation}
$$

In [3]:
def N(V):
    W = np.zeros((2,1))
    W[0,0] = 8*V[1,0]
    W[1,0] = V[0,0] + V[1,0] + 3
    return W

One of the requirements for $N$ to be linear is that $N(V+W) = N(V) + N(W)$ for all vectors $V,W$ in $\mathbb{R}^3$. Any choice of $V$ and $W$ shows that this is not the case, however, and so $N$ is not linear.

In [4]:
V = np.array([[1],[1],[1]])
W = np.array([[1],[2],[3]])
print(N(V + W),'\n')
print(N(V) + N(W))

[[24.]
 [ 8.]] 

[[24.]
 [11.]]


**Exercise 4:** Consider the two transformations, $S$ and $R$, defined below.  Write a Python function that implements the composition $R\circ S$.  Explain why it is not possible to form the composition $S \circ R$.

$$
\begin{equation}
S \left(\left[\begin{array}{r} v_1 \\ v_2 \\ v_3 \end{array} \right]\right) = 
\left[\begin{array}{c}   v_1 + v_2 \\  3v_3 \end{array} \right]
\end{equation}
$$

$$
\begin{equation}
R \left(\left[\begin{array}{r} v_1 \\ v_2  \end{array} \right]\right) = 
\left[\begin{array}{rr} 3 &  0 \\ -1 & 1 \end{array}\right]
\left[\begin{array}{c}   v_1 \\ v_2 \end{array} \right]
\end{equation}
$$
  

We will first write a function for each of $S$ and $R$, and then we will write a function that implements the composition $R \circ S$ by first applying $S$ and then applying $R$ to the output of that transformation. We will confirm that it is working correctly by testing with an example vector.

In [5]:
def S(V):
    W = np.zeros((2,1))
    W[0,0] = V[0,0] + V[1,0]
    W[1,0] = 3*V[2,0]
    return W

def R(V):
    T = np.array([[3,0],[-1,1]])
    W = T@V
    return W

def R_composed_with_S(V):
    W = R(S(V))
    return W

V = np.array([[1],[4],[-2]])
print(R_composed_with_S(V))

[[ 15.]
 [-11.]]


$$
\begin{equation}
R \left(S\left(\left[\begin{array}{r} 1 \\ 4 \\ -2 \end{array} \right]\right)\right) 
= R \left(\left[\begin{array}{r} 5 \\ -6 \end{array} \right]\right)
= \left[\begin{array}{r} 3 & 0 \\ -1 & 1 \end{array} \right] \left[\begin{array}{r} 5 \\ -6 \end{array} \right]
= \left[\begin{array}{r} 15 \\ -11 \end{array} \right]
\end{equation}
$$

It is impossible to form the composition $S \circ R$ because this requires applying the transformation $S$ to the output of the mapping $R$, but $R$ outputs vectors in $\mathbb{R}^2$ and $S$ needs input vectors from $\mathbb{R}^3$.

**Exercise 5:** Create a Python function which implements the transformation: $S:\mathbb{R}^3\to\mathbb{R}^3$, given below. Use the function to provide evidence whether the transformation is **linear** or not.


$$
\begin{equation}
S \left(\left[\begin{array}{r} v_1 \\ v_2 \\ v_3 \end{array} \right]\right) = 
\left[\begin{array}{c} v_1 + v_2 \\  1 \\ v_3+v_1 \end{array} \right]
\end{equation}
$$

Repeat for the transformation $T:\mathbb{R}^3\to\mathbb{R}^3$ is now defined by

$$
\begin{equation}
T \left(\left[\begin{array}{r} v_1 \\ v_2 \\ v_3 \end{array} \right]\right) = 
\left[\begin{array}{c} v_1 + v_2 \\  0 \\ v_3+v_1 \end{array} \right].
\end{equation}
$$

#### Solution:

In [2]:
def S(V):
    W = np.zeros((3,1))
    W[0,0] = V[0,0] + V[1,0]
    W[1,0] = 1
    W[2,0] = V[1,0] +V[2,0]
    return W

V = np.array([[1],[2],[3]])
W = np.array([[2],[1],[3]])

print("V: \n", V, '\n')
print("S(V): \n", S(V), '\n')
print("S(W): \n", S(W), '\n')
print("S(V+W): \n", S(V+W), '\n')
print("S(V)+S(W): \n", S(V)+S(W), '\n')

V: 
 [[1]
 [2]
 [3]] 

S(V): 
 [[3.]
 [1.]
 [5.]] 

S(W): 
 [[3.]
 [1.]
 [4.]] 

S(V+W): 
 [[6.]
 [1.]
 [9.]] 

S(V)+S(W): 
 [[6.]
 [2.]
 [9.]] 



We see that $S(V+W)\neq S(V) + S(W)$. Therefore, the transformation $S:\mathbb{R}^3\to\mathbb{R}^3$ is not linear.

Now, let us consider that the transformation $T:\mathbb{R}^3\to\mathbb{R}^3$ is defined as: 
$$
\begin{equation}
T \left(\left[\begin{array}{r} v_1 \\ v_2 \\ v_3 \end{array} \right]\right) = 
\left[\begin{array}{c} v_1 + v_2 \\  0 \\ v_3+v_1 \end{array} \right]
\end{equation}
$$

It only differs from the previous transformation in terms of the second entry which is zero in this case rather than 1. Let us define the corresponding python function in the code cell below:


In [3]:
def T(V):
    U = np.zeros((3,1))
    U[0,0] = V[0,0] + V[1,0]
    U[1,0] = 0
    U[2,0] = V[1,0] + V[2,0]
    return U

V = np.array([[1],[2],[3]])
W = np.array([[2],[4],[1]])

print("V: \n", V, '\n')
print("T(V): \n", T(V), '\n')
print("T(W): \n", T(W), '\n')
print("T(V+W): \n", T(V+W), '\n')
print("T(V)+T(W): \n", T(V)+T(W), '\n')

k = 5
print("T(kV)): \n", T(k*V), '\n')
print("kT(V)): \n", k*T(V), '\n')

V: 
 [[1]
 [2]
 [3]] 

T(V): 
 [[3.]
 [0.]
 [5.]] 

T(W): 
 [[6.]
 [0.]
 [5.]] 

T(V+W): 
 [[ 9.]
 [ 0.]
 [10.]] 

T(V)+T(W): 
 [[ 9.]
 [ 0.]
 [10.]] 

T(kV)): 
 [[15.]
 [ 0.]
 [25.]] 

kT(V)): 
 [[15.]
 [ 0.]
 [25.]] 



Our conclusions differ from that in the previous case. In this case, $T(V+W) = T(V) + T(W)$ and $T(kV) = kT(V)$. Therefore, we have evidence that $T:\mathbb{R}^3\to\mathbb{R}^3$ is a linear transformation.

Note the difference between $S$ and $T$ in this exercise.

**Exercise 6:** $L:\mathbb{R}^3\to\mathbb{R}^2$ is a **Linear Transformation** . Find $L(kU+V)$ given that $k=7$, 

$$
\begin{equation}
L(U) = \left[\begin{array}{r} 1 \\ 1  \end{array} \right]\hspace{1cm}
L(V) = \left[\begin{array}{r} 3 \\ 1  \end{array} \right]
\end{equation}
$$

#### Solution:

Since $L:\mathbb{R}^3\to\mathbb{R}^2$ is a linear transformation, we can say that $L(kU+V) = L(kU) + L(V)$. Then, we can write $L(kV) = kL(V)$. Therefore, $L(kU+V) = kL(U)+ L(V)$.

Given $k$, $L(V)$ and $L(U)$, we can find $L(kU+V)$.

$$
\begin{equation}
L(kU+V) = (7)\left[\begin{array}{r} 1 \\ 1  \end{array} \right] + 
\left[\begin{array}{r} 3 \\ 1  \end{array} \right] = 
\left[\begin{array}{r} 10 \\ 8  \end{array} \right]
\end{equation}
$$

**Exercise 7:** Let $T:\mathbb{R}^3 \to \mathbb{R}^2$ be defined by $T(X)= AX$, where 

$$
\begin{equation}
A = \left[\begin{array}{rrr} 1 & 0 & 2 \\ 2 & 1 & 1  \end{array}\right].
\end{equation}
$$

Find all vectors $X$ that satisfy $T(X) = \left[\begin{array}{r} 1 \\ 2  \end{array} \right]
$. 


#### Solution:

Given $T(X)$ and $A$, we can find $X$ by solving the following system:

$$
\begin{equation}
AX = \left[ \begin{array}{rrr} 1 & 0 & 2 \\ 2 & 1 & 1\end{array}\right]
\left[ \begin{array}{r} x_1 \\ x_2 \\ x_3  \end{array}\right]=
\left[ \begin{array}{r}1 \\ 2  \end{array}\right]= T(X)
\end{equation}
$$

We can see that there is no pivot in the third column of the coefficient matrix $A$, this means that $x_3$ is a free variable. Therefore, the above system has infinitely many solutions. In other words, there are an infinite number of vectors $X$ in $\mathbb{R}^3$ which get mapped to the vector $AX$ in space $\mathbb{R}^2$.



For instance, when $x_3 = 3$, then we get $x_1 = -5$ and $x_2 = 9$.
So, $$
\begin{equation}
X = \left[ \begin{array}{rrr} -5 \\ 9 \\ 3 \end{array}\right]
\end{equation}
$$


In [5]:
## verifying that T(X) = AX:

A = np.array([[1,0,2],[2,1,1]])
X = np.array([[-5],[9],[3]])

print("AX: \n", A@X, '\n')

# Verifying that X is not unique:
# When x_3 = 0, x_2 = 0, x_1 = 1

X_2 = np.array([[1],[0],[0]])
print("AX_2: \n", A@X_2, '\n')

AX: 
 [[1]
 [2]] 

AX_2: 
 [[1]
 [2]] 



The computation demonstrates that $T(X)$ is same for two different vectors $X$. Therefore, $X$ is not unique.

**Exercise 8:** Let $M:\mathbb{P}_1 \to \mathbb{P}_3$ be a transformation defined by $M(p(x)) = x^3 + p(x)$. Determine whether $M$ is linear or not. 

#### Solution:

In order to determine whether $M$ is linear or not, let us consider two polynomials $p(x)$ and $q(x)$ in $\mathbb{P}_1$. 

$M((p + q)(x)) = x^3 + p(x) + q(x)$ by the general properties of polynomials.

$M(p(x)) + M(q(x)) = (x^3 + p(x)) + (x^3 + q(x)) = 2x^3 + p(x) + q(x)$.

We can see that $M((p + q)(x))$ is not the same as $M(p(x)) + M(q(x))$. Therefore, $M$ is not linear.

We can also see what $M(kp(x))$ and $k(M(p(x)))$ look like.

$M(kp(x)) = x^3 + kp(x)$

$k(M(p(x))) = kx^3 + kp(x)$

It is clear that $M(kp(x))$ and $k(M(p(x)))$ are also different.

**Exercise 9:** Let $S:\mathbb{P}_2 \to \mathbb{P}_3$ and $T:\mathbb{P}_3 \to \mathbb{P}_5$ be two **linear transformations** defined by the rules given below. Define the composition $T\circ S$ and determine whether it is linear or not. Explain why $S\circ T$ is not defined.

$S(p(x)) = x(p(x))$ 

$T(q(x)) = x^2(q(x))$ 

where $p(x)$ is a polynomial in $\mathbb{P}_2$ and $q(x)$ is a polynomial in $\mathbb{P}_3$. 

#### Solution:

Since $S:\mathbb{P}_2 \to \mathbb{P}_3$ and $T:\mathbb{P}_3 \to \mathbb{P}_5$ are two **linear transformations**, $T\circ S:\mathbb{P}_2 \to \mathbb{P}_5$ and it is defined by the following rule:

$T\circ S = T(S(p(x))) = x^2(S(p(x)))$ 

$S(p(x)) = x(p(x))$. Therefore, $T\circ S = T(S(p(x))) = x^2(xp(x))$ 

$T\circ S = T(S(p(x))) = x^3(p(x))$

So, $T\circ S:\mathbb{P}_2 \to \mathbb{P}_5$ is a transformation defined by the following rule:

$T\circ S = T(S(p(x))) = x^3(p(x))$

Let us see if  $T\circ S:\mathbb{P}_2 \to \mathbb{P}_5$ is a linear transformation.
Consider two polynomials $p(x)$ and $q(x)$ in $\mathbb{P}_2$.

$T(S(p(x) + q(x))) = x^3(p(x) + q(x)) = x^3(p(x)) + x^3(q(x)) $ by the properties of polynomials.

$T(S(p(x))) + T(S(q(x))) = x^3(p(x)) + x^3(q(x)) $.

$T(S(kp(x))) = x^3(kp(x)) = kx^3(p(x)))$ by the properties of polynomials.

$kT(S(p(x))) = x^3(kp(x)) = kx^3(p(x)))$

$T\circ S $ is a linear transformation since $T(S(p(x) + q(x))) =T(S(p(x))) + T(S(q(x)))$ and $T(S(kp(x))) = kT(S(p(x)))$.



$S\circ T$ is not defined because the output space of $T$ is not the input space of $S$. The output space of $T$ is $\mathbb{P}_5$ but the input space of $S$ is $\mathbb{P}_2$.

### Matrix Representations

**Exercise 1:** For each of the following linear transformations, find the standard matrix representation, and then determine if the transformation is onto, one-to-one, or invertible.

$(a)$

$$
\begin{equation}
B \left(\left[\begin{array}{r} x_1 \\ x_2 \\ x_3 \\ x_4 \end{array} \right]\right) = 
\left[\begin{array}{c} x_1 + 2x_2 - x_3 -x_4 \\ x_2 -3x_3 +2x_4 \end{array} \right]
\end{equation}
$$

$B$ maps $\mathbb{R}^4$ to $\mathbb{R}^2$ so to find the standard matrix representation of $B$, we have to first apply the formula to each of the four standard basis vectors of $\mathbb{R}^4$.

$$
\begin{equation}
B\left(\left[\begin{array}{r} 1\\0\\0\\0 \end{array}\right]\right)= \left[\begin{array}{r} 1\\0 \end{array}\right] \hspace{1cm} 
B\left(\left[\begin{array}{r} 0\\1\\0\\0 \end{array}\right]\right)= \left[\begin{array}{r} 2\\1 \end{array}\right] \hspace{1cm} 
B\left(\left[\begin{array}{r} 0\\0\\1\\0 \end{array}\right]\right)= \left[\begin{array}{r} -1\\-3 \end{array}\right] \hspace{1cm}
B\left(\left[\begin{array}{r} 0\\0\\0\\1 \end{array}\right]\right)= \left[\begin{array}{r} -1\\2 \end{array}\right] 
\end{equation}
$$

We build $[B]$ by using these images as the columns and then find the RREF using $\texttt{FullRowReduction}$.

$$
\begin{equation}
[B] = \left[\begin{array}{rr} 1 & 2 & -1 & -1 \\ 0 & 1 & -3 & 2 \end{array}\right]
\end{equation}
$$

In [3]:
B = np.array([[1,2,-1,-1],[0,1,-3,2]])
print(lag.FullRowReduction(B))

[[ 1.  0.  5. -5.]
 [ 0.  1. -3.  2.]]


The RREF of $[B]$ has a pivot in every row, but not in the third and fourth columns. Therefore $B$ is onto but not one-to-one.

$(b)$

$$
\begin{equation}
C \left(\left[\begin{array}{r} x_1 \\ x_2 \\ x_3 \end{array} \right]\right) = 
\left[\begin{array}{c} x_1 -x_2 + 8x_3 \\ 4x_1 + 5x_2 - x_3 \\ -x_1 -x_2 + 3x_3 \end{array} \right]
\end{equation}
$$

$C$ maps $\mathbb{R}^3$ to $\mathbb{R}^3$ so to find the standard matrix representation of $C$, we have to first apply the formula to each of the three standard basis vectors of $\mathbb{R}^3$.

$$
\begin{equation}
C\left(\left[\begin{array}{r} 1\\0\\0 \end{array}\right]\right)= \left[\begin{array}{r} 1\\4\\-1 \end{array}\right]\hspace{1cm} 
C\left(\left[\begin{array}{r} 0\\1\\0 \end{array}\right]\right)= \left[\begin{array}{r} -1\\5\\-1 \end{array}\right]\hspace{1cm} 
C\left(\left[\begin{array}{r} 0\\0\\1 \end{array}\right]\right)= \left[\begin{array}{r} 8\\-1\\3 \end{array}\right]
\end{equation}
$$

We build $[C]$ by using these images as the columns and then find the RREF using $\texttt{FullRowReduction}$.

$$
\begin{equation}
[C] = \left[\begin{array}{rr} 1 & -1 & 8 \\ 4 & 5 & -1 \\ -1 & -1 & 3\end{array}\right]
\end{equation}
$$

In [4]:
C = np.array([[1,-1,8],[4,5,-1],[-1,-1,3]])
print(lag.FullRowReduction(C))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


The RREF of $[C]$ has a pivot in every row and column. Therefore $C$ is onto and one-to-one, which means it is invertible.

**Exercise 2:** Let $L:\mathbb{R}^3 \to \mathbb{R}^2$ be the **linear transformation** defined by $L(X)= AX$. 

$$
\begin{equation}
A = \left[\begin{array}{rrr} 1 & 1 & 1\\ 2 & 3 & 4  \end{array}\right]\
\end{equation}
$$

Determine whether $L:\mathbb{R}^3 \to \mathbb{R}^2$ is an invertible transformation or not.



#### Solution:

The **linear transformation** $L:\mathbb{R}^3 \to \mathbb{R}^2$ will be invertible if the matrix $A$ is invertible as $L(X)= AX$. Since $A$ is a $ 2 \times 3 $ matrix, it cannot be invertible. Therefore, $L:\mathbb{R}^3 \to \mathbb{R}^2$ is not an invertible transformation.