## Vector Spaces

In [1]:
import laguide as lag
import numpy as np
import scipy.linalg as sla

### General Linear Systems

**Exercise 1:** Determine the number of solutions to the following system, then find all possible solutions.


$$
\begin{eqnarray*}
5x_1 + 4x_2 - x_3 & = & \hspace{0.3cm} 3\\
x_1 \hspace{1.2cm} + x_3  & = & \hspace{0.3cm} 2\\
-2x_1 + 2x_2 + 4x_3 & = & -3 \\
x_1 + 8x_2 + 7x_3 & = & -3 \\
3x_1 \hspace{1.2cm} - 3x_3 & = & \hspace{0.3cm} 3 \\
\end{eqnarray*}
$$

In [2]:
A_augmented = np.array([[5,4,-1,3],[1,0,1,2],[-2,2,4,-3],[1,8,7,-3],[3,0,-3,3]])
A_augmented_reduced = lag.FullRowReduction(A_augmented)
print(A_augmented_reduced)

[[ 1.   0.   0.   1.5]
 [ 0.   1.   0.  -1. ]
 [ 0.   0.   1.   0.5]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]]


Every column except the last one has exactly one pivot, so there exists a unique solution to this system. That solution is

$$
\begin{eqnarray*}
x_1 & = & 1.5\\
x_2  & = & -1\\
x_3 & = & 0.5
\end{eqnarray*}
$$

**Exercise 2:** Determine the number of solutions to the following system, then find all possible solutions.

$$
\begin{eqnarray*}
5x_1 + 4x_2 - x_3 & = & \hspace{0.3cm} 3\\
x_1  +2x_2 + x_3  & = & \hspace{0.3cm} 0\\
-2x_1 + 2x_2 + 4x_3 & = & -3 \\
x_1 + 8x_2 + 7x_3 & = & -3 \\
3x_1 \hspace{1.2cm} - 3x_3 & = & \hspace{0.3cm} 3 \\
\end{eqnarray*}
$$

In [3]:
B_augmented = np.array([[5,4,-1,3],[1,2,1,0],[-2,2,4,-3],[1,8,7,-3],[3,0,-3,3]])
B_augmented_reduced = lag.FullRowReduction(B_augmented)
print(B_augmented_reduced)

[[ 1.   0.  -1.   1. ]
 [ 0.   1.   1.  -0.5]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]]


Niether the third nor the last column have pivots, so there exist an infinite number of solutions to this system. If we parametrize $x_3 = s$ then the following is a solution to the system for any $s \in \mathbb{R}$

$$
\begin{eqnarray*}
x_1 & = & 1 + s\\
x_2  & = & -0.5 - s\\
x_3 & = & s
\end{eqnarray*}
$$

**Exercise 3:** Determine the number of solutions to the following system, then find all possible solutions.

$$
\begin{eqnarray*}
5x_1 + 4x_2 - x_3 & = & \hspace{0.3cm} 3\\
x_1  +2x_2 + x_3  & = & \hspace{0.3cm} 0\\
-2x_1 + 2x_2 + 4x_3 & = & -3 \\
x_1 + 8x_2 + 7x_3 & = & -3 \\
3x_1 \hspace{1.2cm} - 3x_3 & = & \hspace{0.3cm} 3 \\
\end{eqnarray*}
$$

In [ ]:
## Code solution here.

**Exercise 4:** Construct an example of an inconsistent system with 2 equations and 4 unknowns.  Check your example by using $\texttt{FullRowReduction}$

In [7]:
C_augmented = np.array([[2,4,-3,3],[4,8,-6,5]])
C_augmented_reduced = lag.FullRowReduction(C_augmented)
print(C_augmented,'\n')
print(C_augmented_reduced)

[[ 2  4 -3  3]
 [ 4  8 -6  5]] 

[[ 1.   2.  -1.5  0. ]
 [ 0.   0.   0.   1. ]]


**Exercise 5:** Explain why it is not possible for a system with 2 equations and 4 unknowns to have a unique solution.  Base your argument on pivot positions.

The augmented matrix that represents a system with 2 equations and 4 unknowns must can have at most 2 pivots since it has only 2 rows.  This means that one of the first four columns does not have a pivot and corresponds to a free variable in the system.  The guaranteed existence of a free variable means the system not have a unique solution.

**Exercise 6:** Write a function that accepts the augmented matrix for a system and returns the number of free variables in that system.  Make use of $\texttt{FullRowReduction}$ in the $\texttt{laguide}$ module. 

In [ ]:
## Code solution here.